<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Men_black-overlay</name>
   <tag></tag>
   <elementGuidId>2e38627b-198f-4a99-8614-1090e92a6557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.black-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Menú'])[1]/preceding::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad54a542-52b0-4ff1-84db-bfc89a09f977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-overlay</value>
      <webElementGuid>cb34c3b3-b057-43d2-a437-00994629d592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-loading[@class=&quot;loadingPpal&quot;]/ngx-spinner[1]/div[@class=&quot;black-overlay&quot;]</value>
      <webElementGuid>05cb526d-e6f7-427f-a6f6-a592b976b76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menú'])[1]/preceding::div[6]</value>
      <webElementGuid>b62c8ca9-f301-46bf-b93d-276bbc916d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/preceding::div[6]</value>
      <webElementGuid>0afba0c1-7370-40ca-872f-be594949ffbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>ef1ce22a-c4bd-477b-a593-2b1fe3432d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
