<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Al seleccionar una obligacin ustedesta _826bd5</name>
   <tag></tag>
   <elementGuidId>4ef2636a-75db-41ae-9da4-55bbe6a177a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alert-modal']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9acc48e9-b47b-42ae-82a7-373ef93a3659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>11b884bd-571f-4447-8fee-27405bb5c61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Al seleccionar una obligación ustedesta habilitado para formular reclamos</value>
      <webElementGuid>c5ac3abc-5a38-4471-a4ca-af654c43fde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-modal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]</value>
      <webElementGuid>275bb435-10bf-4d89-adbe-aac6d56c20b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-modal']/div/div/div</value>
      <webElementGuid>bd5cd17e-2da4-4079-8e21-b6f5329bb292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[1]</value>
      <webElementGuid>19f30229-aebc-41a9-8f83-159c35571445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFE 000000111165051157 COOMULCAR'])[1]/following::div[8]</value>
      <webElementGuid>ea7b263a-e53d-49e8-b440-f5ad67ed0ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©2016 Experian Information Solutions, Inc. Experian Marketing Services All rights reserved'])[1]/preceding::div[3]</value>
      <webElementGuid>fbf6c73b-f10c-4f38-9399-4aca705cd116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©2016 Experian Information Solutions, Inc. Experian Marketing Services All rights reserved'])[2]/preceding::div[6]</value>
      <webElementGuid>fc22f129-5020-4ac0-9435-3ad03e831933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dispute/div[2]/div/div/div</value>
      <webElementGuid>6b9eab15-b82d-417b-baf0-dcc7a8359fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Al seleccionar una obligación ustedesta habilitado para formular reclamos' or . = 'Al seleccionar una obligación ustedesta habilitado para formular reclamos')]</value>
      <webElementGuid>9519cf81-8873-409e-984c-86fd419bb69d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
