<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JustificacinSeleccioneDerecho de Petici_3b31c5</name>
   <tag></tag>
   <elementGuidId>513abc99-b86f-4be7-b99e-97fa9ff2db6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea947017-dc0a-4b12-bd3b-05c7b2e1bb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3 col-sm-4 col-12</value>
      <webElementGuid>545fd80e-dcdd-483e-bf60-ac597c105120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Justificación*SeleccioneDerecho de PeticiónTérmino de Permanencia</value>
      <webElementGuid>7a2c637d-3d58-4be4-ba25-810372c49ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-1&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/app-form-holder-search[@class=&quot;matExpansionPanelBody&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;show-obligacion form-element&quot;]/div[@class=&quot;formulario-field form-element&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-4 col-12&quot;]</value>
      <webElementGuid>9f872e41-4500-4387-b641-03e9a9606ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]</value>
      <webElementGuid>5f10ef0d-1248-4db4-bbae-356a77d0a6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Obligación'])[1]/following::div[1]</value>
      <webElementGuid>84c2ca67-3e67-47d7-9cc7-7566dda66ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[3]</value>
      <webElementGuid>ed660221-c575-4407-8ad5-ad2672a8986e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>3578e040-11cd-42e3-a18f-7d3b1c3e071b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Justificación*SeleccioneDerecho de PeticiónTérmino de Permanencia' or . = 'Justificación*SeleccioneDerecho de PeticiónTérmino de Permanencia')]</value>
      <webElementGuid>c276d0ce-cbdf-4736-a3a1-3dfac2cdafe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
