<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__modal-btn</name>
   <tag></tag>
   <elementGuidId>88419fd7-d2b4-4dd7-a49e-24c6b8d193d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-confirm-modal-action > div.modal-dialog > div.modal-content > div.modal-body > div.modal-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alert-confirm-modal-action']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13dc307a-6fd5-4048-8450-97d3aaf05101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-btn</value>
      <webElementGuid>8868d9ef-7f1e-4acc-9582-a8e9645cd41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-confirm-modal-action&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-btn&quot;]</value>
      <webElementGuid>d2ceac85-342d-44dd-9ac5-db2b23f6ea9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-confirm-modal-action']/div/div/div/div</value>
      <webElementGuid>c544e3f0-57ec-4b4f-9299-09c5527e8e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::div[2]</value>
      <webElementGuid>05b99148-bfca-4dd1-8614-d4e93637ffcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[4]/following::div[5]</value>
      <webElementGuid>53efa32d-a236-44c3-b84f-ae91f3412f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[5]/preceding::div[1]</value>
      <webElementGuid>bbb3d71c-3379-4210-bc60-3ccafdafc274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::div[1]</value>
      <webElementGuid>bd2a29f6-a9d7-441d-a5b8-96e49b3a94bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>3ed464e7-97b9-44ac-bc5a-f9df560a061d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
