<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reclamos</name>
   <tag></tag>
   <elementGuidId>ef74777f-6150-49be-865d-53e99083a1d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='disputeMenu']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cce3d9e4-1d7e-40e4-9cf6-6b7ad6157c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-8</value>
      <webElementGuid>786599ce-1c57-4de8-8634-b3294476b674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reclamos</value>
      <webElementGuid>2e92fd0f-9a7a-4527-896c-658deb701503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disputeMenu&quot;)/div[@class=&quot;row row-dispute&quot;]/div[@class=&quot;col-sm-8&quot;]</value>
      <webElementGuid>592e8238-3385-4850-b3ec-ee87b3303380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='disputeMenu']/div/div[2]</value>
      <webElementGuid>fe3ea2c8-d500-4bd3-9c81-1a90c3018705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alertas y comentarios'])[1]/following::div[3]</value>
      <webElementGuid>3e84ce74-becb-4b74-b518-7b609dace6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/following::div[3]</value>
      <webElementGuid>cca69fb3-f236-4f32-951a-d09f168dde87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reclamos'])[2]/preceding::div[3]</value>
      <webElementGuid>24d4271e-9a5f-4dac-9951-2a224c90f862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>88a9ed30-6491-48fb-91d1-8b2276c92b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Reclamos' or . = 'Reclamos')]</value>
      <webElementGuid>1c1e8e89-83ad-4562-8386-0c3582a5174c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
