<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a944d657-87b9-4550-8167-d9c96a5289cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='operationMassive']/li/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#operationMassive > li > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1cf66034-562f-47cc-8969-caf20cd45c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>7263c663-87c6-4975-8a62-faed5d2e028a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/audit_sl.png</value>
      <webElementGuid>efd27330-ca42-4dd8-a0af-09b5d3a82b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-tooltip-6</value>
      <webElementGuid>18988cfd-cf22-4398-a135-e4ca6e8d9950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationMassive&quot;)/li[1]/img[1]</value>
      <webElementGuid>2fa5f4e4-ae4d-4b06-8d8f-2e5be3c54c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='operationMassive']/li/img</value>
      <webElementGuid>f6a53935-2bdc-4016-9893-a6e9bbbe8a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/li/img</value>
      <webElementGuid>2fd1a198-e22d-46b2-b0bd-ccdc1fce4118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/audit_sl.png']</value>
      <webElementGuid>0b91ec5b-dde8-4212-8f1c-ba43a1931a7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
