<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>79cbf933-a8ef-4056-a578-ab04fb548823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuModification']/li/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ng-star-inserted > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ecd72ba7-0722-49fc-b041-80c9fe8b93d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fb1ffc6a-6f7b-4744-beea-7f40dca6ca14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/menu_modify_sl.png</value>
      <webElementGuid>7e0da370-197b-4b05-92be-d53c31e09215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-tooltip-15</value>
      <webElementGuid>6ca6ea6b-bd08-47b8-9259-7c6ba2b1e2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuModification&quot;)/li[@class=&quot;ng-star-inserted&quot;]/img[1]</value>
      <webElementGuid>8cd7e962-fdc1-42da-9d3f-c242f11a6d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuModification']/li/img</value>
      <webElementGuid>f128f8dc-2bf8-4826-bc1e-c73b3e13ecbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/li/img</value>
      <webElementGuid>7a938a03-b714-4fd6-9ed1-b89f25c66efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/menu_modify_sl.png']</value>
      <webElementGuid>62da8222-9fa8-4e6c-a8be-36016aafbef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
