<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>2390f273-4d1b-4684-8dc5-2a80548e3186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuProcess']/li/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menuProcess > li > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>97c4318e-2f2d-4b7f-aa9b-7e4f8def0864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>14fbabc9-f2e0-4e44-b088-0b1f29c9f534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/process.png</value>
      <webElementGuid>57a1035f-913d-4d36-95da-46f8c18711cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-tooltip-7</value>
      <webElementGuid>f0bf5a1b-9b4d-4756-92f8-3311a9645ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuProcess&quot;)/li[1]/img[1]</value>
      <webElementGuid>f2920f38-54c1-430a-a42c-4bfca05bda75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuProcess']/li/img</value>
      <webElementGuid>e6407e8d-2326-44b7-91e9-35384183982e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/li/img</value>
      <webElementGuid>8b857ff4-2f33-4ffa-85db-967a90138774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/process.png']</value>
      <webElementGuid>432808fe-d214-4967-b3e9-2e951f8d031f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
