<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Atencin ciudadano_d-block</name>
   <tag></tag>
   <elementGuidId>be0d9157-eaa1-44e3-955a-3ccca06fd79e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logo datacredito']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.d-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>51c41ef6-ef10-4824-a841-ed59f7188fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo datacredito</value>
      <webElementGuid>a4ec07c7-5033-4bd1-929e-d1c8f463be0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block</value>
      <webElementGuid>54447922-ef24-49a5-9dec-78fa4e1c9b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/logos/mainlogo-datacredito.png</value>
      <webElementGuid>1be807fc-f7f4-41a4-b80b-71c9814912cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-header[@class=&quot;ng-star-inserted&quot;]/header[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-5&quot;]/div[@class=&quot;cont-logo&quot;]/a[1]/img[@class=&quot;d-block&quot;]</value>
      <webElementGuid>b5ef68f7-c06a-4936-bbb7-efc2a18bbbf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo datacredito']</value>
      <webElementGuid>5a5c1a7e-22aa-44de-b777-d2339a90114e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>b47b162b-a23b-4c39-8d6a-4b58e08c038d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo datacredito' and @src = './assets/images/logos/mainlogo-datacredito.png']</value>
      <webElementGuid>969531f9-65b8-40ab-9b80-2fdb7107af9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
