<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono Celular_btn btn-inverse2 pull_ad7ef9 (1)</name>
   <tag></tag>
   <elementGuidId>1a316bb3-7c0c-4564-b893-6697ea1dfda9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/article/app-formulation-dispute/div[1]/section/form/section[4]/mat-accordion/mat-expansion-panel/div/div/div/div/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-inverse2.pull-right.right10.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b34fe039-9d51-4b1d-bed6-6045770e7077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-inverse2 pull-right right10 ng-star-inserted</value>
      <webElementGuid>1777a950-19b9-4328-ab81-da8156ec5ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>246f3bab-31da-4cf6-99de-ac5b8cba5e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Listo</value>
      <webElementGuid>684a4b20-f709-410c-a49c-9c80c8f3a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/div[@class=&quot;show-obligacion3 form-element&quot;]/div[@class=&quot;formulario-field form-element&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-inverse2 pull-right right10 ng-star-inserted&quot;]</value>
      <webElementGuid>89b58ffd-1f7e-4b75-972b-8e82c733cc65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Listo']</value>
      <webElementGuid>6441337e-dab9-4559-bf67-721cdcfe83d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div[2]/div/input</value>
      <webElementGuid>f2425d3f-315a-43e3-aa62-584a360ee844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/input</value>
      <webElementGuid>9fdea0d8-0e09-4bd1-b413-f57de8920a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>205af965-be93-47a9-b02a-e8f55d1cf781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
