<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__emailForm</name>
   <tag></tag>
   <elementGuidId>6db1d453-e3e8-42cf-9f29-f75605ea57e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56fb5b76-393b-4746-bbfd-6a7e569b150a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7be4b6e4-6d3d-44b4-a519-ccc53210a4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>emailForm</value>
      <webElementGuid>772b9ca0-7b21-4e41-afc1-892e9e6f2625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailForm</value>
      <webElementGuid>df058803-f207-45ac-9e68-7d8237f65323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailForm</value>
      <webElementGuid>7de8e973-bfcb-4fc2-a7ab-1d66b9866356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailForm&quot;)</value>
      <webElementGuid>4e4a99dd-c920-4adc-b9d6-e99eecadb764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailForm']</value>
      <webElementGuid>0801f8f3-6f6c-42ff-95a7-98b6e9dd746d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/input</value>
      <webElementGuid>9577ce52-1f8e-4f9c-8f15-5ea67b7ba4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emailForm' and @name = 'emailForm']</value>
      <webElementGuid>ab21dda8-f273-4877-9809-543e85fde230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
