<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asignar_accept-assing-modal</name>
   <tag></tag>
   <elementGuidId>8d032eec-7eb8-4335-9453-dfd37c187f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-assing-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-assing-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d3088bb-946c-4b59-8551-7fcebab10430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary asignar03</value>
      <webElementGuid>9aa732ae-8473-4460-8515-2da2322c39c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-assing-modal</value>
      <webElementGuid>ce101788-bd4f-41e1-a90c-21db615fe1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fd013d2-6273-46a5-bb03-2adc4a7db66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asignar</value>
      <webElementGuid>8c839a7f-76c0-48b9-9b9b-a2fb6e9d1e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-assing-modal&quot;)</value>
      <webElementGuid>f99fb4d8-9f13-4590-977f-35f952401d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-assing-modal']</value>
      <webElementGuid>c2259d01-1544-425e-b2fb-292393331f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignModal']/div/div/div/div/input[2]</value>
      <webElementGuid>00a7b781-2e85-44e3-8901-9eac0a6002f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[2]</value>
      <webElementGuid>d8b77df6-4352-4111-9ace-2e8bf17bf766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-assing-modal' and @type = 'button']</value>
      <webElementGuid>b6213cfd-83af-4e67-9201-42eb19b79503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
