<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accept-alert-modal (2)</name>
   <tag></tag>
   <elementGuidId>d5032690-efd6-4b4b-b910-0669de29d7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19853a07-d9d0-47dc-bdeb-0873fe8341fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8f981417-8f87-492f-88fc-a859e0f9ec80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-modal</value>
      <webElementGuid>ad63a83a-6e3f-4edc-86e7-ce661698bbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>704b9ea9-c0d8-43a3-a304-92850457333b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>395a26c5-e268-47a6-9ee7-7e105bc03c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-modal&quot;)</value>
      <webElementGuid>804404c6-2d94-4ec2-8a21-62555fe4117a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-modal']</value>
      <webElementGuid>3710e973-3c39-4525-ace5-cf71c9a62b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>872adf68-733f-4f67-bc96-2eff043123e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>6653c689-3008-4c77-b344-3baa76bfa195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-modal' and @type = 'button']</value>
      <webElementGuid>1ba0d64f-f2f8-46fc-b6f5-47ee87e09662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
