<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radica Caso_accept-alert-modal (1)</name>
   <tag></tag>
   <elementGuidId>95a045f5-0eb1-4209-b5ce-086fdb290118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71c8d32b-c0df-47a9-8472-5fd55ba762af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>20d00a57-7c29-40fa-8dcf-f3a0dc3f4c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-modal</value>
      <webElementGuid>94a34516-b014-4d32-8ee0-7ba1c6564ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d4ce274-ef5a-4c30-950c-c4774eb08f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>8dbd2b01-e032-4f38-b015-0cd723b8ab30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-modal&quot;)</value>
      <webElementGuid>e9f8bbe3-766e-4983-ae9f-8ca5550b2090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-modal']</value>
      <webElementGuid>feedc8bd-f4c3-4618-b64a-50843db87c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>67f1cd60-d8fa-4c0e-abf4-18fcdddf435b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>c6ae714b-96af-4f6f-b76e-56c228c2796d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-modal' and @type = 'button']</value>
      <webElementGuid>a51239b7-8010-4de0-9d05-b7f7e66998a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
