<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accept-alert-confirm-action-massive</name>
   <tag></tag>
   <elementGuidId>37cdbe78-9ca5-4320-a9ae-8a630baa9246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-confirm-action-massive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-confirm-action-massive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ab352f9-706f-4626-aeb7-c5d18074fb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c22bfcfe-0920-4801-9ef1-791972352396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-confirm-action-massive</value>
      <webElementGuid>bd662b74-9ea3-47f2-ba6f-db3cf9b1a4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0c5fb7b-7f29-4786-b2e7-b6775fd7706e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>f9c4f908-facf-44be-9d45-83eb9d5a9645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-confirm-action-massive&quot;)</value>
      <webElementGuid>fd0ad731-58ac-467d-86c3-6816888bc2c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-confirm-action-massive']</value>
      <webElementGuid>6df70e2d-6f1c-4069-b3f8-ae30dcda9f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-confirm-action-massive']/div/div/div/div/input[2]</value>
      <webElementGuid>4672e06e-0984-43bf-b673-49c9cbb0ce75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input[2]</value>
      <webElementGuid>8c8c71ab-0aad-4217-97b8-a7f01633bfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-confirm-action-massive' and @type = 'button']</value>
      <webElementGuid>69792a43-43f0-4756-9a12-8e3723e8a586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
