<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_www.datacredito.com.co_termConditions_1ccce0 (1)</name>
   <tag></tag>
   <elementGuidId>a3e3ead5-eb5f-4dd8-921c-fac864d43a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termConditionsEmailDispute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#termConditionsEmailDispute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39761e17-12ac-43a0-af50-ae339a586a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termConditionsEmailDispute</value>
      <webElementGuid>41da95fa-7cb3-4faa-b4e0-83d1ee28d4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3be530e7-eb98-4e16-8330-3a3473fc2abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termConditionsEmailDispute&quot;)</value>
      <webElementGuid>408ff6e8-de3a-4a4b-8cc5-1dd709448ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termConditionsEmailDispute']</value>
      <webElementGuid>125005c6-8c3a-477e-ba0c-4effc0c5a338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>790ba830-39b4-4f03-b693-abf94542e252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termConditionsEmailDispute' and @type = 'checkbox']</value>
      <webElementGuid>89659fa1-413a-49a2-9f45-25135c3d610c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
