<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CCS 000000116118277170 CREDITOS FINAN_d34f0e</name>
   <tag></tag>
   <elementGuidId>081ce6e1-88ed-433e-910c-0566e835a65a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Asignar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.asignar01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9ecf2b9-93e2-4d98-b2dc-17f6ca9c4423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary asignar01</value>
      <webElementGuid>467e48d8-680c-44c8-b603-9c7950696533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#assignModal</value>
      <webElementGuid>aacdae17-437b-4ad6-afa5-8ebb23008af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3921e8c9-689a-4c69-a7f4-7d717b6fd5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>88fe413d-f737-48e3-a36e-8b284b4f0abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85f7ec9b-88b9-415f-9ea6-3589f0e92b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asignar</value>
      <webElementGuid>9a41eef0-90d4-4ff7-8fb8-7cc8862a1176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-assignment[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;select-action&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;selecion-group&quot;]/div[@class=&quot;radio-container&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-check&quot;]/input[@class=&quot;btn btn-primary asignar01&quot;]</value>
      <webElementGuid>27050ca5-55d6-4975-8b9a-3a072bcc0026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Asignar']</value>
      <webElementGuid>346c4fc9-8289-4c5f-bfbd-fbbe3acedf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2aa20fa1-5f6e-4532-a740-c3e04ea1d35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@href = 'javascript:void(0)' and @type = 'button']</value>
      <webElementGuid>c28e4ac2-1f47-4ddc-8b28-44978ed179f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
