<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accin Aprobar_accept-motivo-aprobacion (4)</name>
   <tag></tag>
   <elementGuidId>560eb1fe-66ba-4b25-8ff4-ac6293cefcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-motivo-aprobacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-motivo-aprobacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41974341-f23c-423c-90be-e97f1cd3faaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8ad51481-528c-4e61-afa9-73a2d249bafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-motivo-aprobacion</value>
      <webElementGuid>2c302e8a-0f91-4232-a692-2ff3df481174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbca4b91-3e8f-4509-841b-3d415c46b249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>2f061245-14f4-4cbc-8179-9b2225e6e6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-motivo-aprobacion&quot;)</value>
      <webElementGuid>b702c143-2a68-4ca7-97ec-4f9ff41cdad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-motivo-aprobacion']</value>
      <webElementGuid>2097aa18-dc99-4802-9244-922802dac537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motivo-aprobacion']/div/div/div/form/div/input[2]</value>
      <webElementGuid>0196e699-0240-41a9-97e3-4e551bae181d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/form/div/input[2]</value>
      <webElementGuid>5edddd79-9ff7-4096-9dec-7c05c80f0042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-motivo-aprobacion' and @type = 'button']</value>
      <webElementGuid>2e286137-12ad-4fe5-96ba-79cb9ebbd11b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
