<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accin Aprobar_accept-motivo-aprobacion</name>
   <tag></tag>
   <elementGuidId>75c9b922-3a56-4d18-8b10-caeb2a1ed52a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-motivo-aprobacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-motivo-aprobacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>195ef735-15c8-4d55-b7d4-fda169a96005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>a5d87b57-9e99-40d8-9e91-be8a78d0cfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-motivo-aprobacion</value>
      <webElementGuid>e86e750c-d3d9-406f-b85b-1091e16b1168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62b6a68b-8984-4510-85cc-43b27811e90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>07441ba9-3a25-4288-8a30-0397cfdd9cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-motivo-aprobacion&quot;)</value>
      <webElementGuid>ca3a792a-68a9-48eb-9b98-342d359e62c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-motivo-aprobacion']</value>
      <webElementGuid>97e005ca-94f3-46d2-aac0-25dc6e9d589f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motivo-aprobacion']/div/div/div/form/div/input[2]</value>
      <webElementGuid>bc8a68a9-3087-4a63-9d85-cb824a5e1407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/form/div/input[2]</value>
      <webElementGuid>f3217704-ae44-4f3a-9c4c-09d53639a8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-motivo-aprobacion' and @type = 'button']</value>
      <webElementGuid>ff3d1c46-2a40-4e77-9280-4c50b1e1708d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
