<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Proceed  Without Changes_btn btn-secondary</name>
   <tag></tag>
   <elementGuidId>631f2277-1773-4cd9-89e0-11d6c0659ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/article/app-operations-massives/section[4]/form/section/div/div/div[1]/div[4]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-transmit > div.modal-dialog > div.modal-content > div.modal-body > div.modal-btn > input.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bbc8cf5-6b76-45b0-bd4e-ab688d3d537e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>0613360a-1cb5-4470-9513-5afb6b891051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>819933ac-7ca1-4b8f-a21b-178d9c5bc87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>58d2ed47-e18a-477b-94e0-63e995db9da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-transmit&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-btn&quot;]/input[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>2c986d86-6f48-4483-9177-e58570a7ddac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Cancelar'])[4]</value>
      <webElementGuid>ae330e72-e38a-4c42-af33-8d71ddd73d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-transmit']/div/div/div/div/input</value>
      <webElementGuid>9b0a5c9b-2666-4825-9be4-5b124a267dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>4d7e29d1-f2d5-45b2-8487-1fe23cdcf1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>b8e87cdd-dde5-476a-b60a-b7137e1bc393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
