<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accin Cerrar Caso_accept-close-case-modal</name>
   <tag></tag>
   <elementGuidId>cdd96c16-0c09-4bf7-bebc-c344a6932214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-close-case-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-close-case-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d82c0a8-5cf1-48e7-b168-4d830c3d5720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8ea4c4ff-5d43-4cc8-8947-380e40e5cb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-close-case-modal</value>
      <webElementGuid>58260f95-fd1f-4b75-9b82-0ccfd94144d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93210c39-f34e-4e63-b286-b9b0f81e81b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>8da27e89-1831-4237-820f-1c9ecd336508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-close-case-modal&quot;)</value>
      <webElementGuid>95837261-8b4c-4a5a-875d-bb634666ac9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-close-case-modal']</value>
      <webElementGuid>a9863bbf-bf1b-498a-8162-34d51a4643ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close-case-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>a316c790-127e-4375-8ef2-43714552e5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/input[2]</value>
      <webElementGuid>aa142572-92c0-4b0e-a7a1-9632b149613f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-close-case-modal' and @type = 'button']</value>
      <webElementGuid>ca507ded-9e90-497b-b88a-0abacec16d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
