<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono Celular_btn btn-inverse2 pull_ad7ef9</name>
   <tag></tag>
   <elementGuidId>891469be-37a1-4cfe-864b-917c99354df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Listo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-inverse2.pull-right.right10.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8be0a5d4-aad5-4987-b507-80b00647748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-inverse2 pull-right right10 ng-star-inserted</value>
      <webElementGuid>551a6040-1f7d-4dfe-a01e-76fc8fb61d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6fef8ba-862f-4c5e-b872-2dcc62e26383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Listo</value>
      <webElementGuid>f4b9b664-ae2c-4abb-bfbd-44f20580ceae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/div[@class=&quot;show-obligacion3 form-element&quot;]/div[@class=&quot;formulario-field form-element&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-inverse2 pull-right right10 ng-star-inserted&quot;]</value>
      <webElementGuid>3c054a1c-9ddb-486c-a282-cdf661e03e9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Listo']</value>
      <webElementGuid>ad5c074f-3da6-4b84-9a64-94dc750a4889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div[2]/div/input</value>
      <webElementGuid>c29bb9ae-89aa-4196-9d8f-e10ac7f7e27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/input</value>
      <webElementGuid>833fe131-830a-4cf1-b94e-e4bce19cb23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c998522b-f5dd-4864-9480-6d469a4c9120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
