<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmar Correo electrnico_reemailDi_160b6f (1)</name>
   <tag></tag>
   <elementGuidId>89733bdf-ba7b-4dca-947b-e52cf1acc996</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reemailDisputeform']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reemailDisputeform</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6576d943-2dc3-44a2-b5f4-1dd16fd9478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-star-inserted ng-dirty ng-invalid</value>
      <webElementGuid>51b3318e-9952-4374-8eba-5af3d2b27877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reemailDisputeform</value>
      <webElementGuid>630a8b80-d8d3-4604-acea-64570a1f1b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>f1f6320c-58f9-41dd-8392-47f5ecaeee7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reemailDisputeform</value>
      <webElementGuid>789b09ee-f7d3-44b7-891f-fc1a7546c103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa080cad-d43b-42b3-b16b-a7c705577e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reemailDisputeform&quot;)</value>
      <webElementGuid>f46f1c0c-bc07-499e-9fe0-8df07c62d8c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reemailDisputeform']</value>
      <webElementGuid>84716a30-8020-4cec-88bd-14700db0c1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div/div[2]/input</value>
      <webElementGuid>3404dff5-eba9-4290-938c-6f89c06aee96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ff2c16c8-fc81-487a-8645-cebe00195363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reemailDisputeform' and @name = 'reemailDisputeform' and @type = 'text']</value>
      <webElementGuid>b44317d5-dd06-4c5b-8d35-8324e20bb305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
