<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha de anlisis_btn btn-primary pull-right (3)</name>
   <tag></tag>
   <elementGuidId>c52509fe-f2db-405a-8bb2-f3c8d9e579ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Aprobar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f65cb7a-d9f6-4332-8924-77ad2f0507d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>4cfeafd1-3eef-433b-a49c-92a7d0cb67f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#motivo-aprobacion</value>
      <webElementGuid>c5020797-eea0-414e-9d9a-8e4c2c935294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>287ad7c4-4d08-4c58-9a45-9b3d8a4a6cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6ff279fc-b70b-4f3b-ad3f-6340c26bf809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>382d4240-7792-42ba-9be0-16c830d17bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aprobar</value>
      <webElementGuid>21198d29-e12e-4eaf-a0bf-272523c7b6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-disapprove-approve[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;observacion typeLetterBody&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-primary pull-right&quot;]</value>
      <webElementGuid>cfb685c9-b6eb-4197-8798-ddf990d1d442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Aprobar']</value>
      <webElementGuid>d6b9ca6e-7bf7-49e2-aed8-c371e9407163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>a2a0e257-46f0-4a54-b05e-bababf9f9408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@href = 'javascript:void(0)' and @type = 'button']</value>
      <webElementGuid>dc888975-98a5-47b6-b82e-992d5f4a97a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
