<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_accept-delete (1)</name>
   <tag></tag>
   <elementGuidId>1fbc9e29-5937-4191-9a22-b1f59029bbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>792ebc7e-7e40-4ab2-9cc2-cb39fbd60171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>e371ed86-cf38-41f1-918c-b1c16ce8f3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-delete</value>
      <webElementGuid>3923dc55-5188-4432-b5c0-379131b9f405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac5c2974-48e6-4d84-9cd6-51403da26db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>6ac14adf-84c6-4c24-99d2-360d2b211afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-delete&quot;)</value>
      <webElementGuid>0297bb7a-ca3d-4d42-95a9-8df60973d8cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-delete']</value>
      <webElementGuid>fd87180b-d9ad-422d-88c6-b931ce043903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-delete']/div/div/div/div/input[2]</value>
      <webElementGuid>6289eb0f-33bf-4068-9c21-125c1ba909f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input[2]</value>
      <webElementGuid>ce706dba-1dc0-4e9d-a4fc-60d90b141d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-delete' and @type = 'button']</value>
      <webElementGuid>6c357775-a35d-40a1-96b0-fb300fbcad2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
