<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alert Model_continuar (1)</name>
   <tag></tag>
   <elementGuidId>1583ad1a-82ed-47bb-a11c-88e329557e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;continuar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='continuar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>040c5496-4f71-4508-a514-a9cf9336cbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right ng-star-inserted</value>
      <webElementGuid>bc921320-214c-4722-b01e-105acff4a6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-ratify</value>
      <webElementGuid>a539133d-2a3c-4ad6-9252-1707b4c749c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continuar</value>
      <webElementGuid>79bd1256-a56c-45c6-b5b1-2ec98ded5223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a033dd06-f574-466d-8707-d0622f9dabf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>a768d986-8ef2-43fb-99d1-e54983302770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-redicar-detail-holder-page[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;typeLetterBody&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-primary pull-right ng-star-inserted&quot;]</value>
      <webElementGuid>c8d242d2-ec58-4276-a7f0-c3ed174d8965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='continuar']</value>
      <webElementGuid>46435733-1027-419a-a39e-7262f9b713f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>fc9a1e67-77fb-4f48-8533-6d1106518025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'continuar' and @type = 'submit']</value>
      <webElementGuid>76e69197-2057-4b07-9729-9fe4ffb326bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
