<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_puede consultar su historia de crdito_bdb83d (1)</name>
   <tag></tag>
   <elementGuidId>284bf72f-4eeb-4a2f-a1ea-9fbfea81c524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='assign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;assign&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0605a92c-6dee-462c-a7d5-4212351d2ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right right10 ng-star-inserted</value>
      <webElementGuid>9acf3113-58b8-4363-8ef1-48c4c620ba4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#assing-modal</value>
      <webElementGuid>ebddd534-47b8-4ff5-82fe-a3efa11847c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>c07d91cb-e180-43bd-abbd-da9bad263ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assign</value>
      <webElementGuid>09e84a2f-0a62-47a5-b57c-91f10967c43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02d5e671-000f-4394-8de3-9be61cd23a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Analizar Reclamo</value>
      <webElementGuid>421a04a6-af3d-4cf6-b8a8-c3b8236f87d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-answer-modification-detail-holder[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;btn-container typeLetterBody&quot;]/input[@class=&quot;btn btn-primary pull-right right10 ng-star-inserted&quot;]</value>
      <webElementGuid>ad8c397b-7545-42e4-9221-6443567fc4cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='assign']</value>
      <webElementGuid>ad94f025-2a55-47fa-b113-b94a54d5abaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>70a146bc-f731-4f91-82d5-cb8751add116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'assign' and @type = 'button']</value>
      <webElementGuid>4c66d101-41fd-4f59-a7bd-e355374875ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
