<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estado Proceso_checkboxListCom</name>
   <tag></tag>
   <elementGuidId>01400ee1-6461-4653-b38f-b21f845b59d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkboxListCom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkboxListCom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ff48398-3183-4bf9-a90e-95c3b2a943e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkboxMyList</value>
      <webElementGuid>b8e863d2-0764-4730-9036-e1fba85ce21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxListCom</value>
      <webElementGuid>ee9e9412-c929-41c9-980b-21ed984e202a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxListCom</value>
      <webElementGuid>6e7129dc-06f0-435c-844e-a1a85ca8347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44cf44ef-3658-463e-98a5-58778a1d0485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>31472774</value>
      <webElementGuid>c5f3ef9d-0e53-4aad-bbb4-1e6cf562cc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxListCom&quot;)</value>
      <webElementGuid>b67dcec0-6004-4964-ab17-ccb95c72583e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkboxListCom']</value>
      <webElementGuid>5e1e8d0f-9d59-4e87-a16c-a72bef356d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='no-more-tables']/table/tbody/tr/td/input</value>
      <webElementGuid>c87c3764-7710-494e-b029-8a898446a006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>51562b7c-3e87-4d03-8088-58d0a240d87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkboxListCom' and @name = 'checkboxListCom' and @type = 'checkbox']</value>
      <webElementGuid>4cc9f9c3-2809-48e6-9215-1acb0eb0a92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
