<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alert Model_continuar (2)</name>
   <tag></tag>
   <elementGuidId>06280af2-ebc3-4842-b0e8-cbc274eefaa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;continuar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='continuar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>484cc097-4b62-4da7-bb4a-f535b131ef39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right ng-star-inserted</value>
      <webElementGuid>01fb3138-f35b-4b62-b146-159ef5494088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-ratify</value>
      <webElementGuid>0ce0c36c-2bdb-41f8-8433-db4d17d6344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continuar</value>
      <webElementGuid>9847da58-d16e-4132-963c-c59bacf5d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>021f31fb-7a72-4ba6-8ce1-e018f1f1a92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>43c62e64-85d7-4a37-9709-7eb9cc54247f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-redicar-detail-holder-page[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;typeLetterBody&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-primary pull-right ng-star-inserted&quot;]</value>
      <webElementGuid>ebf7595e-e880-45bd-9440-a437fef61f0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='continuar']</value>
      <webElementGuid>7ae90982-de62-4e10-8bcb-da746ddb4b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>d229e2ac-f55b-4c42-b73b-d04b23959242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'continuar' and @type = 'submit']</value>
      <webElementGuid>cf317845-45ff-4a8c-9f90-474397843963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
