<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono Celular_btn btn-inverse2 pull_ad7ef9</name>
   <tag></tag>
   <elementGuidId>891469be-37a1-4cfe-864b-917c99354df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-inverse2.pull-right.right10.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/article/app-operations-massives/section[4]/form/section/div/div/div[1]/div[4]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46c43f97-9102-46f3-ae3e-2cf08ff381b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-inverse2 pull-right right10 ng-star-inserted</value>
      <webElementGuid>e35094cd-eccd-4935-b1be-dab131d3e8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f596bea-2bca-4200-9bba-36ddf24dcc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Listo</value>
      <webElementGuid>6392faa7-7290-416f-a9f4-901d1be04927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/div[@class=&quot;show-obligacion3 form-element&quot;]/div[@class=&quot;formulario-field form-element&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-inverse2 pull-right right10 ng-star-inserted&quot;]</value>
      <webElementGuid>af1c9bd6-78f3-4d11-8f40-2d9eb2fb535f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Listo']</value>
      <webElementGuid>2937310d-d5db-4613-bce7-813e481dee07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div[2]/div/input</value>
      <webElementGuid>bcded12a-db3c-4293-84c3-9bb3830ffbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/input</value>
      <webElementGuid>d8dcae01-249c-4de5-9909-b94f45f65128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>afee93ac-68bf-4396-aaff-f41cfcfe9107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
