<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ObservationComment_continuar</name>
   <tag></tag>
   <elementGuidId>5be6214d-1f9a-4e68-9ed7-e1f50e5b4345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='continuar'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0864c7e6-d166-47ee-b5f1-9ec6be6a242a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right ng-star-inserted</value>
      <webElementGuid>a5247518-e5c5-448a-b37d-ece0e7a8a6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continuar</value>
      <webElementGuid>f2fe43f4-8a28-493a-bc02-f2bf3f33987c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53d5847a-fb28-4e8f-82ec-5b83af438199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>01172f77-477b-4c96-96e3-827745350842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-redicar-detail-holder-page[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;typeLetterBody ng-star-inserted&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-primary pull-right ng-star-inserted&quot;]</value>
      <webElementGuid>f2c4fead-8197-41ff-b343-df5e575dbea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='continuar'])[2]</value>
      <webElementGuid>1c0ae410-abdf-4501-a2cc-a17fd71b54cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>3e625fdb-67aa-4457-ab60-61a87aff8a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'continuar' and @type = 'button']</value>
      <webElementGuid>29ca3c67-ac0d-43e3-80b6-72de2ca4f45c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
