<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consultar por_idFilter3 (4)</name>
   <tag></tag>
   <elementGuidId>038befe0-233f-4f7a-8345-1b6be9e769d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idFilter3Id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idFilter3Id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9e41efb-75c0-47ae-a65a-8ab9d521d8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f36ae7e3-ea55-424d-9acc-9e5350c87590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>39f39401-e105-4bbd-8392-ffe5ee31ca4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idFilter3Id</value>
      <webElementGuid>e038d289-7d04-4a27-9fa3-678563f3b47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0f11dedf-cfb4-4a43-8496-a1cddb2620f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idFilter3</value>
      <webElementGuid>b46760c6-e3ef-4218-a588-591fb136d2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>3379e4ee-ffad-4696-96a1-6156bd1bf8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese el número de reclamo</value>
      <webElementGuid>7b4ab7f6-2985-4c83-a382-5d924258a31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21aa763a-e699-4733-a0c8-2693dae2583f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d07a8d51-e4d0-4cb9-a8c2-c293bb44fcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idFilter3Id&quot;)</value>
      <webElementGuid>8f9e5f48-42db-4da6-bea2-75acbd2acf06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idFilter3Id']</value>
      <webElementGuid>fdb3672d-8d2c-409e-af5c-111873346cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bc66993a-73b1-4b49-aab9-349f4ee03b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idFilter3Id' and @name = 'idFilter3' and @placeholder = 'Ingrese el número de reclamo']</value>
      <webElementGuid>d6fd140e-b938-426f-900b-6ab1ee7a7c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
