<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consultar por_btn btn-primary ml-1 (1)</name>
   <tag></tag>
   <elementGuidId>aeb12961-1fbe-498f-8b23-97dead8787a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.ml-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Consultar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98a5ce84-45fd-4efe-9cff-1273cbaa841c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ml-1</value>
      <webElementGuid>64a1d7b5-4f92-40d0-a391-1fa315369eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cfb18c37-dffc-4dd7-a857-fe5dd1f10796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Consultar</value>
      <webElementGuid>1cd43b6d-e1ae-4779-8eff-8c4b2954fcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-get-lists[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;filter-container typeLetterBody&quot;]/div[@class=&quot;filter-section&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;filter-btn&quot;]/input[@class=&quot;btn btn-primary ml-1&quot;]</value>
      <webElementGuid>0c2bc65d-70b5-42dd-92d2-0e4c117fb984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Consultar']</value>
      <webElementGuid>c12534c5-6c68-4c72-8d75-2f3109739e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input[2]</value>
      <webElementGuid>5b9adde9-5127-4119-a323-5e8ddcbe29a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>921d72a0-16b1-4e36-8b57-652991a24e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
