<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Proceed  Without Changes_accept-transmit (1)</name>
   <tag></tag>
   <elementGuidId>7677f7cd-0811-414b-850b-3d4d7b9a5404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-transmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-transmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e6dc96a-bbae-4174-a3b7-f5b97496805c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>75fbc28f-a2bd-42af-bd13-816c4f22baed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-transmit</value>
      <webElementGuid>8dfb54a0-42d8-480b-ab2d-9e9d38c3d7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80bee093-b458-4571-93f5-fb876580cfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>7fa08453-9854-4182-9f1c-6e5d256a5a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-transmit&quot;)</value>
      <webElementGuid>a75cd569-b703-45df-b8d5-7163c706101d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-transmit']</value>
      <webElementGuid>f2be6082-3a01-4d0e-84e3-f699d1175f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-transmit']/div/div/div/div/input[2]</value>
      <webElementGuid>e45c1ef8-5e51-4947-bc9d-081e66980919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input[2]</value>
      <webElementGuid>38698959-1ffc-4ca9-9ce2-6e38f5fb6c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-transmit' and @type = 'button']</value>
      <webElementGuid>51e97b97-039e-4c25-b0a4-3209508ef14e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
