<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CAC 055063164130891100 FINANCIERA COM_98135d</name>
   <tag></tag>
   <elementGuidId>403a48b0-4880-4c78-b917-7425027514d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.asignar01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Asignar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a96405fd-8ad9-4081-9212-5674402afb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary asignar01</value>
      <webElementGuid>ae8b1f55-9411-4162-b4bf-ce1d560ea913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#assignModal</value>
      <webElementGuid>ccbb8bdb-431b-4c5b-ba7b-0cf3a3564b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>ca269cb4-f1bd-4664-8c92-54a1579603d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>861ca105-ef7a-403f-b93c-8d527fd165c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>132e5a71-a9ae-4ca6-b03e-e54d9686917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asignar</value>
      <webElementGuid>8bc0f6f8-0c81-4654-be7b-a26547908cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-assignment[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;select-action&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;selecion-group&quot;]/div[@class=&quot;radio-container&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-check&quot;]/input[@class=&quot;btn btn-primary asignar01&quot;]</value>
      <webElementGuid>b7807608-c983-429f-9479-946f6da88f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Asignar']</value>
      <webElementGuid>81d96a71-798b-40bb-bed0-a27cac623ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d0749672-33d6-45ec-8693-bbb2e060883d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@href = 'javascript:void(0)' and @type = 'button']</value>
      <webElementGuid>d4574376-b881-437a-a93e-c59590741818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
