<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accept-assing-modal (2)</name>
   <tag></tag>
   <elementGuidId>d969ea4b-5763-4406-9df2-b40d0ba00f34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-assing-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-assing-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f18527e-e953-4ddb-ab5b-31e19d325bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>81348ac5-499b-499f-b5c9-2c2ce23185fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-assing-modal</value>
      <webElementGuid>836cdb95-f7f7-4878-b0b5-5420b048a85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ceb36d9-4da4-433b-b610-df9387c62ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>a1d39571-c887-4bdf-a1c0-7dc4ecc945f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-assing-modal&quot;)</value>
      <webElementGuid>d6ac321c-0e70-4eb8-8dc1-153ac9c1bcc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-assing-modal']</value>
      <webElementGuid>476da8f3-b3b4-4a96-afb5-e3fc888c40a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assing-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>ad674a23-7cbe-4f3a-8bf8-53326b28afec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[2]</value>
      <webElementGuid>3cc900a6-c4fd-4963-a56a-31ef02ed4150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-assing-modal' and @type = 'button']</value>
      <webElementGuid>094b9596-207e-44eb-bdaf-b7ec3a4d3907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
