<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radica Caso_accept-alert-modal (2)</name>
   <tag></tag>
   <elementGuidId>68308c7b-a8d7-4561-8c04-2fbe83a83a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a48efd-aee2-4eb2-9d0e-e3dba8ac558a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9e9ef048-bb6d-4a9d-aefe-fa07770d1aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-modal</value>
      <webElementGuid>e5e74be8-1b95-4a11-bc8d-55b36edde9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>620c48d7-7f36-4151-98cd-d8471eb9e480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>f775cb2f-a018-4b5d-80ce-6e09e7db6d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-modal&quot;)</value>
      <webElementGuid>81c975aa-276d-40ed-a2a0-00fa76bbbb89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-modal']</value>
      <webElementGuid>0876aad8-1070-471d-b46a-fe4c7422db30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>ba996e6b-a421-45c3-8348-ccb278a555da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>65b7e688-7659-43a7-830b-7269845c64f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-modal' and @type = 'button']</value>
      <webElementGuid>10e57384-2264-4e37-a7f3-dc92b1d4dd03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
