<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accin Aprobar_accept-motivo-aprobacion (3)</name>
   <tag></tag>
   <elementGuidId>93580436-f820-4825-9ddf-4f845914d75d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-motivo-aprobacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-motivo-aprobacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ada9054-f63d-454f-9b32-b6a248e121c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1bbad241-74d3-4874-b5d2-1a4e05cdaf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-motivo-aprobacion</value>
      <webElementGuid>395b04ae-1be5-49b1-9406-b32992da24c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d596259-ec5d-44b5-8b68-eb1d1d713949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>3eb602bf-d04d-468e-9041-61477bba82fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-motivo-aprobacion&quot;)</value>
      <webElementGuid>b72f598b-5ed1-4f85-b95a-1c3a3c756874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-motivo-aprobacion']</value>
      <webElementGuid>a02d72f4-543a-4ffa-a0d8-820d384f2eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motivo-aprobacion']/div/div/div/form/div/input[2]</value>
      <webElementGuid>05e4c050-9250-4f05-b590-2c9b8afe056c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/form/div/input[2]</value>
      <webElementGuid>42fd64bb-87c6-430c-95d0-3f8dcff4ddea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-motivo-aprobacion' and @type = 'button']</value>
      <webElementGuid>90722c98-d60b-4da5-8294-701b91822873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
