<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accept-alert-error-modal</name>
   <tag></tag>
   <elementGuidId>85fccbdc-60f6-4647-9028-5221e5ef7cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-error-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-error-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c16c26b0-ca1e-4647-8e43-8f066e9b5f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>fe9fc44b-687d-42c7-83a4-37d6de5d6626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-error-modal</value>
      <webElementGuid>35b707aa-fe04-4191-b593-a32f8f680f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6b502a9-4440-4ee3-b994-dfaf171fec21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Return</value>
      <webElementGuid>de458518-04fd-423a-9092-f48fa3b34857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-error-modal&quot;)</value>
      <webElementGuid>3b915790-1e2b-4c61-a075-2beeda2dfabc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-error-modal']</value>
      <webElementGuid>c8b304c2-247e-4133-af58-487938db8c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-error-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>28ae9374-57d3-4829-aa90-07c68546075a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input[2]</value>
      <webElementGuid>32bbe557-9257-40c2-8fe3-2ad1650c0ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-error-modal' and @type = 'button']</value>
      <webElementGuid>92eaefed-58fb-424f-95fd-977c3826c58e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
