<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acceptAnswer</name>
   <tag></tag>
   <elementGuidId>2ce35f98-1725-4b66-84a1-9f643c5aa127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01f9b17f-b2ed-4ad9-bb10-c5edd56622e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptAnswer</value>
      <webElementGuid>21fdd3d3-8230-4207-8731-fd9adf70b828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6f776b6c-261f-457d-9a80-d0b6aa916717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptAnswer&quot;)</value>
      <webElementGuid>516dc4e0-46c9-4ff6-ad16-ef51919339af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptAnswer']</value>
      <webElementGuid>2f85fd19-3bac-4f8c-aaa5-8ad935e61bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>36ee1c9d-ded5-4eaf-ad2c-20f7fa7b9791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'acceptAnswer' and @type = 'checkbox']</value>
      <webElementGuid>6bc580b7-e88a-479c-acc9-62d9f84d7c52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
