<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accept-alert-confirm-modal-action</name>
   <tag></tag>
   <elementGuidId>7350098b-617b-4046-8ea5-5cbfa3a4e683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-confirm-modal-action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-confirm-modal-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86161e02-c918-409f-b565-53a6207d2452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>23960188-6115-45b0-a557-501ecb267a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-confirm-modal-action</value>
      <webElementGuid>00f32c56-cc4b-47cb-a55a-cba29a1fb420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f129c6b-5468-403e-8a2d-f47d10067e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>03fc7697-5f7f-4b83-8f21-5dc3c5c92e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-confirm-modal-action&quot;)</value>
      <webElementGuid>c9bd5153-2343-4ea9-a4b4-6fdba5be6485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-confirm-modal-action']</value>
      <webElementGuid>3442682e-247a-4473-a47a-393279f2dd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-confirm-modal-action']/div/div/div/div/input[2]</value>
      <webElementGuid>380d43e5-3a3d-4cae-8020-25b100d647fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input[2]</value>
      <webElementGuid>ea8c3761-c2ae-45d4-900d-97ce8fe9e56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-confirm-modal-action' and @type = 'button']</value>
      <webElementGuid>83c1b565-47ee-461d-ad7f-94cf39cc9181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
