<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo Electrnico_emailDisputeform (2)</name>
   <tag></tag>
   <elementGuidId>139b0ace-4d4c-4132-bfe2-75f35772b273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailDisputeform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailDisputeform']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b418a2a8-c73e-4b75-9edf-0c9c3def8563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d594adba-8e71-4904-97ed-bb222f568477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailDisputeform</value>
      <webElementGuid>05a20836-46b2-4fce-aba4-375b762ae4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>727634c5-efc1-4e70-be4d-f4d1b4e82c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailDisputeform</value>
      <webElementGuid>dfaa8f28-f3c0-4ef0-b55c-a62faf172e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e55aefb0-b197-4d98-96c1-c36ccd2ec526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailDisputeform&quot;)</value>
      <webElementGuid>bcedc700-fcd1-45ff-b557-d686f4a60317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailDisputeform']</value>
      <webElementGuid>5fd5dd36-086b-499d-a77f-0f6ffba5af5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div/div/input</value>
      <webElementGuid>1385e27d-b25d-4fb4-abfa-f44a63c75626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/input</value>
      <webElementGuid>750ada19-ea79-4915-ba53-f862e7369e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emailDisputeform' and @name = 'emailDisputeform' and @type = 'text']</value>
      <webElementGuid>8b1a11ba-1696-49b0-bf60-ac914a9a6f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
