<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_www.datacredito.com.co_termConditions_1ccce0 (2)</name>
   <tag></tag>
   <elementGuidId>a657969e-9c3d-423b-b2e5-be4c2fa4ece1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termConditionsEmailDispute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termConditionsEmailDispute']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc8cee7e-09cc-4870-a207-cbe63964f812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termConditionsEmailDispute</value>
      <webElementGuid>b022788d-5ef4-4c19-98e5-a4248c582a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>81c0002f-02ea-4492-a626-30aa32dccb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termConditionsEmailDispute&quot;)</value>
      <webElementGuid>f5bb1223-eccd-42d6-a48e-ab097e55192e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termConditionsEmailDispute']</value>
      <webElementGuid>bfff45cb-2cfb-466e-a5bd-9439c1942420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>20c9e23d-facf-4253-97b3-91241689f478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termConditionsEmailDispute' and @type = 'checkbox']</value>
      <webElementGuid>a9334b42-b3e0-4911-be50-59dba11aef65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
