<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CCF 000000111468986143 BANCOLOMBIA SU_861bf6</name>
   <tag></tag>
   <elementGuidId>b8b09db6-d527-4051-96d3-85666d2355fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Asignar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.asignar01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>359e12ee-dd2a-49ab-9f90-168c2667f8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary asignar01</value>
      <webElementGuid>898692f6-7c8c-4b45-bda6-a0f4084c3bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#assignModal</value>
      <webElementGuid>e9788ae6-8903-42a6-bb95-b0fac07744e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>90265e39-5601-4aa6-9517-065c3e3b96d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b3db813c-3109-45e4-a492-924cc35a346d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf91e884-26f3-43db-afd7-0581b40761a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asignar</value>
      <webElementGuid>f8e1cf0e-660a-41d4-abc2-dd3861e71e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-assignment[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;select-action&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;selecion-group&quot;]/div[@class=&quot;radio-container&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-check&quot;]/input[@class=&quot;btn btn-primary asignar01&quot;]</value>
      <webElementGuid>b3504192-8d26-4f66-b38e-b492a2228765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Asignar']</value>
      <webElementGuid>d78be38b-4d6a-4a06-ab53-4adc13972892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>de134f2b-155d-4cd5-83d5-f0c534eab812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@href = 'javascript:void(0)' and @type = 'button']</value>
      <webElementGuid>7c1c11cd-e5bf-4bdd-b3af-2765b9a4e013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
