<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consultar por_btn btn-primary ml-1 (3)</name>
   <tag></tag>
   <elementGuidId>c9fd4496-4d83-4d36-af9c-9d2835ea52b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Consultar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.ml-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8542533d-735f-4edc-8dd4-9c22445cbf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ml-1</value>
      <webElementGuid>b616a82c-b80d-4b71-a38d-2c20a7cabf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e7fdfd29-af85-4f0c-9be1-ad326ef2286b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Consultar</value>
      <webElementGuid>c73418b5-da84-4880-9c10-86f4cb2b240e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-get-lists[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;filter-container typeLetterBody&quot;]/div[@class=&quot;filter-section&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;filter-btn&quot;]/input[@class=&quot;btn btn-primary ml-1&quot;]</value>
      <webElementGuid>3f70ab5f-aeec-42b0-9891-79c424409686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Consultar']</value>
      <webElementGuid>3a53c3dd-0cb3-443b-b4a9-dc8f9e5d016c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input[2]</value>
      <webElementGuid>f4b183dd-9fb3-4e31-82b9-6965b7817e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>bb642e1c-a5ab-4b41-9119-dfcb8989badf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
