<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Error, ha ocurrido un error inesperad_24e9a4</name>
   <tag></tag>
   <elementGuidId>598dca10-2cfd-4240-bf25-1796f340373b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-alert-error-modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-alert-error-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18ce5b76-83ea-4b25-b5a9-c824f3112829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>2dd6a551-5743-476f-a3f6-3d7b8e489a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-alert-error-modal</value>
      <webElementGuid>21223776-9c43-4f4a-82a6-f077b24f496c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f389961-2a1d-4e8e-9141-190f740e1c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Volver</value>
      <webElementGuid>01b9b1b3-51a1-4401-bd51-bbef7a1015b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-alert-error-modal&quot;)</value>
      <webElementGuid>198629ea-dc09-4997-a77c-ed991dc7f1e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-alert-error-modal']</value>
      <webElementGuid>a09ba48f-8a89-4f27-98a5-22aad0abf804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-error-modal']/div/div/div/div/input[2]</value>
      <webElementGuid>310c5bea-6b71-4965-8cd1-16eb59bf6069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input[2]</value>
      <webElementGuid>fbf42a9c-d115-4b25-a764-a7732c832207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-alert-error-modal' and @type = 'button']</value>
      <webElementGuid>9a8e712d-bb3d-406e-8644-13a7e3bbe7d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
