<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accin Aprobar_accept-motivo-aprobacion (2)</name>
   <tag></tag>
   <elementGuidId>b80d025b-8d93-40ce-bf0b-cf2ad51b045b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-motivo-aprobacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-motivo-aprobacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7d5eb78-dc38-4eee-a907-e9d1c6ea04dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>3dbf6d2a-3173-4e32-8ebd-5d40444c87a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-motivo-aprobacion</value>
      <webElementGuid>68720a5c-e561-4722-9fe4-36d6de9388c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5156af76-fb93-4984-999c-3e30809ecda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>afd9802e-0a1b-4c26-8fc8-de98132e3d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-motivo-aprobacion&quot;)</value>
      <webElementGuid>9c9faaa1-c208-4338-a6d6-babf1f8368e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-motivo-aprobacion']</value>
      <webElementGuid>1c0f7fc7-1b46-41d0-a7f2-d3358a76756a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motivo-aprobacion']/div/div/div/form/div/input[2]</value>
      <webElementGuid>d4fa2491-bf90-46a1-a6fd-9deb95d94f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/form/div/input[2]</value>
      <webElementGuid>7b43c8a1-9032-4980-b662-e2ab12da1c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-motivo-aprobacion' and @type = 'button']</value>
      <webElementGuid>467ca2a8-2d14-43b7-9a4a-a3fdf73911e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
