<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vector Comportamiento_goMyList (2)</name>
   <tag></tag>
   <elementGuidId>bd25b190-8c6e-4fd2-954f-08c299cccfb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='goMyList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;goMyList&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a16a4a50-77b2-4434-8553-a5d3d9166f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right right10</value>
      <webElementGuid>5b14bfd1-549e-4a86-ac52-109f0a9817bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goMyList</value>
      <webElementGuid>8f788b9d-43f4-4372-b61e-0cf20520b214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e74e268-d034-4d49-8926-d498537d0d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ir a mi lista</value>
      <webElementGuid>4c9ce669-d46b-4540-8691-f8af9d14319e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-answer-modification-detail-holder[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;btn-container typeLetterBody&quot;]/input[@class=&quot;btn btn-primary pull-right right10&quot;]</value>
      <webElementGuid>872eba39-5d69-49c2-ad5d-2bdd9af86fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='goMyList']</value>
      <webElementGuid>d155aa32-f1c8-4d41-8768-70c0d3843d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>efe15515-bdf1-42ea-a1a1-f92af824efe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'goMyList' and @type = 'button']</value>
      <webElementGuid>9bc3adc9-36b4-4d6e-aa32-d2eaa4b2f201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
