<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consultar por_btn btn-primary ml-1 (2)</name>
   <tag></tag>
   <elementGuidId>5df66f20-ea6e-4612-9be8-b57e8f52c230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Consultar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.ml-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0882b388-51d0-4865-8fd9-56b70eb7e758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ml-1</value>
      <webElementGuid>289a9fd6-4cbd-48d2-900d-6870c1ebd0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>917272f8-6c0b-41d4-99de-f0a7b288f97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Consultar</value>
      <webElementGuid>4c4a97a6-4043-45be-97fb-e34e871672ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-get-lists[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;filter-container typeLetterBody&quot;]/div[@class=&quot;filter-section&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;filter-btn&quot;]/input[@class=&quot;btn btn-primary ml-1&quot;]</value>
      <webElementGuid>b3aa3aa5-986a-4cd4-a8f8-d918f308bb05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Consultar']</value>
      <webElementGuid>6248c065-dead-43dc-8fd3-8dc0ee752a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input[2]</value>
      <webElementGuid>38f90fee-03a7-40d9-81f1-cb4a708dca09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>51213de7-8784-4fcd-817e-273c739bf9e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
