<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accin Aprobar_accept-motivo-aprobacion (1)</name>
   <tag></tag>
   <elementGuidId>4f42f38b-c892-463d-8a42-e12190a4f7cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-motivo-aprobacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-motivo-aprobacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7067b12f-14fb-45ac-b0fa-d68451f546de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>94cc2622-cfdb-47a2-9759-e2256e7ac169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-motivo-aprobacion</value>
      <webElementGuid>0ff030d1-adbf-4137-90e9-cee435cffddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56234583-88e0-44dd-997e-daae23f585ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>335ec041-c297-4e00-88d3-209e583bd924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-motivo-aprobacion&quot;)</value>
      <webElementGuid>247f8933-fa38-4fec-9e04-a0de96bd762d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-motivo-aprobacion']</value>
      <webElementGuid>17150e09-3ca1-4646-9e80-732bdc40a296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motivo-aprobacion']/div/div/div/form/div/input[2]</value>
      <webElementGuid>ad26a87f-f41d-4e81-a214-b5f995d0ba33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/form/div/input[2]</value>
      <webElementGuid>5fb9ffea-4da8-4c25-ac74-9c09f4aa1df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-motivo-aprobacion' and @type = 'button']</value>
      <webElementGuid>84357f32-9600-4484-9b7d-849bb20c254e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
