<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_www.datacredito.com.co_termConditions_1ccce0</name>
   <tag></tag>
   <elementGuidId>03d2fe58-33aa-4ac7-aa1f-e0ca01ef9e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termConditionsEmailDispute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#termConditionsEmailDispute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72d5034d-1761-411a-a1ca-bd3960b47ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termConditionsEmailDispute</value>
      <webElementGuid>a424fec6-1446-4d76-ae0c-164e349e4350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>09fd33ff-efdf-4464-a825-7a946979ab37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termConditionsEmailDispute&quot;)</value>
      <webElementGuid>74fac582-d93f-4916-b86b-5e3e3b874f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termConditionsEmailDispute']</value>
      <webElementGuid>8c6b8fea-555d-4196-89d0-865eedac112f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>0ab8ae50-91ce-4cb1-b52a-599f112843bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termConditionsEmailDispute' and @type = 'checkbox']</value>
      <webElementGuid>5d6825de-dea8-4f8b-a316-f57a1452f8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
