<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmar Correo electrnico_reemailDi_160b6f (2)</name>
   <tag></tag>
   <elementGuidId>94a0a995-9c80-4763-a7be-09230efa739e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reemailDisputeform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reemailDisputeform']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f21b9f9b-eed7-4e47-97b0-20472c86e913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-star-inserted ng-dirty ng-invalid</value>
      <webElementGuid>bbf27118-7e6e-403a-89f3-74d2ad7c1fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reemailDisputeform</value>
      <webElementGuid>0c2d1010-412a-4162-8218-8a296d32dcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>674ae5d7-f46f-466a-94ee-da6502b4965b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reemailDisputeform</value>
      <webElementGuid>2de358eb-023d-4360-b6fb-73ddcff311db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db385a14-3e11-4bca-801c-cab7017cf700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reemailDisputeform&quot;)</value>
      <webElementGuid>e21f153f-4733-4c1c-81fa-836ab6814dcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reemailDisputeform']</value>
      <webElementGuid>3e44f8f4-bbe1-4da9-99cd-daaa1a1b3d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div/div[2]/input</value>
      <webElementGuid>18f10607-0226-46fa-9285-f3a408bf9c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>391970e1-2b48-42c2-8064-74548c993fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reemailDisputeform' and @name = 'reemailDisputeform' and @type = 'text']</value>
      <webElementGuid>59f2bb29-cf2e-4ae8-96e8-75351fd4ee5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
