<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha de anlisis_btn btn-primary pull-right (4)</name>
   <tag></tag>
   <elementGuidId>3da9f062-3e2e-4989-afc9-414aaed82b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Aprobar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe017298-3366-4b31-af3f-79d7042b0215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>d40b8819-afe4-43b6-84a8-4259630392bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#motivo-aprobacion</value>
      <webElementGuid>a869dcb6-8b7f-42a1-b812-2639762628d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>7dd79df2-57c5-426d-9fbf-21642f1b86d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>66998caf-7d1b-4ff6-9bfc-c78bb5c9e525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2872c19e-9c97-4b7f-8bc3-c11777eb8931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aprobar</value>
      <webElementGuid>ca41a32d-2414-4458-9981-55743b8a3f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-disapprove-approve[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;observacion typeLetterBody&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;btn-container&quot;]/input[@class=&quot;btn btn-primary pull-right&quot;]</value>
      <webElementGuid>f2815651-5b3a-4e17-9051-08690d3b2b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Aprobar']</value>
      <webElementGuid>fed2478b-e530-4b12-9d01-f06cf86095b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>13bfefc1-7ebf-4d2f-aea7-b5dd937ad5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@href = 'javascript:void(0)' and @type = 'button']</value>
      <webElementGuid>70beb9cc-ee3b-41ea-ad85-74a3863d0d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
