<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Proceed  Without Changes_accept-transmit</name>
   <tag></tag>
   <elementGuidId>fe923d5e-b5ac-445b-a070-7d7a855b0434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept-transmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-transmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90bda184-df28-4612-abcf-4a4693a9e6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1c9b5f2b-9e5b-497b-ac61-3d171d1ef281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-transmit</value>
      <webElementGuid>a824d41e-a338-4da0-a402-56e498635ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58556df5-0525-435b-b7fe-1f974df06ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>b3769a22-0849-45c5-8459-a03637b8f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-transmit&quot;)</value>
      <webElementGuid>34518edd-2930-4cb9-990a-945622e50902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-transmit']</value>
      <webElementGuid>39789c86-cf0f-46d2-be23-603e800f1b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-transmit']/div/div/div/div/input[2]</value>
      <webElementGuid>14530678-a47e-493f-89cb-11e7b0c5e4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input[2]</value>
      <webElementGuid>8e366d71-088d-47b9-bdf2-6128616565f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-transmit' and @type = 'button']</value>
      <webElementGuid>e0cb73b6-2c92-48d6-a241-e5790b83c069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
