<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_accept-delete</name>
   <tag></tag>
   <elementGuidId>a952cae3-4f94-4821-a7df-ee078a565141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/article/app-redicar-detail-holder-page/div[3]/div/div/div/div/input[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5e1f5d7-0263-48b6-b34e-4c16360635c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>94f1c127-f191-4221-9cea-6d1f62710001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-delete</value>
      <webElementGuid>ebce0e4e-021e-4c4d-bb68-92036626c876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04aff981-a3f5-42c3-8945-e3ca17e7252a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>6cc1feeb-195d-4c4f-9539-ff11aba6e563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-delete&quot;)</value>
      <webElementGuid>96ef58cc-3e31-47e9-a460-4b8679362050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-delete']</value>
      <webElementGuid>0f0ef378-a1d1-42b6-98a4-64f4a4ddf25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-delete']/div/div/div/div/input[2]</value>
      <webElementGuid>6b0d2cd8-6c00-4bd8-8076-c89031698d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input[2]</value>
      <webElementGuid>ac5ad320-288f-4d0e-8fff-46e4b64f3f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-delete' and @type = 'button']</value>
      <webElementGuid>43a9b9e4-7b87-4c9a-b405-e3a5bc5a5884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
