<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Acepto los trminos y condiciones (2)</name>
   <tag></tag>
   <elementGuidId>185f8c35-b2c9-4811-b941-a156f77ca5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.checkConditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='www.datacredito.com.co'])[1]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c4b15a51-dcad-42b0-8b35-480db7772254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkConditions</value>
      <webElementGuid>98164bfa-f605-454c-ba39-cc7cb631cc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>termConditionsEmailDispute</value>
      <webElementGuid>767ecc7a-fdac-4d8a-adec-ec25e262884b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acepto los términos y condiciones*</value>
      <webElementGuid>9c10fcbd-61f6-4be7-b43d-ac9f026b144b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-formulation-dispute[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/section[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/section[@class=&quot;select-action typeLetterBody ng-star-inserted&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;acc-info&quot;]/div[@class=&quot;checkbox-container&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;checkConditions&quot;]</value>
      <webElementGuid>4b717366-8881-4eb5-99f8-747143f389d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.datacredito.com.co'])[1]/following::label[1]</value>
      <webElementGuid>18f6dc60-954d-40b0-b5eb-e697e3e909ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y condiciones'])[1]/following::label[1]</value>
      <webElementGuid>f7bdf774-93bd-4bb4-b777-4d08dd036de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acepto los términos y condiciones']/parent::*</value>
      <webElementGuid>2ce79197-3768-4fe2-bd15-278426de8429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>05d00e90-355d-4037-b339-8e01464b7762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Acepto los términos y condiciones*' or . = 'Acepto los términos y condiciones*')]</value>
      <webElementGuid>45fa155a-d89a-408d-9885-19d6934a1d3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
