<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Formulacin Reclamos Operador (2)</name>
   <tag></tag>
   <elementGuidId>e603be45-a142-49fd-b471-43f48dc5eebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FormOper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='FormOper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f89c0a9d-9c39-401e-af71-a75354fac5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mi-lista ng-star-inserted</value>
      <webElementGuid>a18ad806-a3b0-4ffb-83bb-c21ce79f3324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormOper</value>
      <webElementGuid>b9cf708a-b64d-4e89-8ebf-a117778a8f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulación Reclamos Operador</value>
      <webElementGuid>0d8f1e70-035e-41cd-a88b-11c546d662d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormOper&quot;)</value>
      <webElementGuid>4ebdb6b0-fc29-4930-a36b-77c34266a6fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='FormOper']</value>
      <webElementGuid>3c371c8b-1a03-4ac5-9f88-3b3089e5d1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulación Reclamos Entidad'])[1]/following::li[1]</value>
      <webElementGuid>94420cd6-f84c-44a4-a6ac-6fa7655f991d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio > Formulación Reclamos Entidad'])[1]/following::li[2]</value>
      <webElementGuid>9182d088-a4b3-4239-99f5-d37775b324fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Formulación Reclamos Operador']/parent::*</value>
      <webElementGuid>99a14b83-88f7-4897-88c9-c823eeeaf47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[2]</value>
      <webElementGuid>7586db95-ce6a-4206-87f6-77a0c3b50105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'FormOper' and (text() = 'Formulación Reclamos Operador' or . = 'Formulación Reclamos Operador')]</value>
      <webElementGuid>92d28fbd-8221-4f25-adbd-8edfd165e844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
