<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Modificacin (1)</name>
   <tag></tag>
   <elementGuidId>bd2d1590-d7b3-4608-a5a4-3164ee90b926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuModification > li.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuModification']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c0778563-db62-4bcd-89f3-2ab6e61f2bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>fe6de7e5-74d8-4234-88a1-96bbf382bd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificación</value>
      <webElementGuid>51357a85-3c43-4c24-98af-e2f59365e083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuModification&quot;)/li[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>d9ea2d0f-3e56-4a2d-afcf-ab8cac4f6afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuModification']/li</value>
      <webElementGuid>413dd8e7-4167-4f40-859a-4cbb0f9878cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reclamos'])[1]/following::li[1]</value>
      <webElementGuid>8a17d0a9-0c24-4651-9163-937666aada0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alertas y comentarios'])[1]/following::li[2]</value>
      <webElementGuid>1b45fb66-5b15-48a4-904d-7284b9e4ad05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operaciones masivas'])[1]/preceding::li[1]</value>
      <webElementGuid>3a7da23b-e099-46f5-8d5b-361748ba13be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/li</value>
      <webElementGuid>bda87983-a57c-4ddc-a2a2-6805c8eb3ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Modificación' or . = 'Modificación')]</value>
      <webElementGuid>b8a656d4-9099-42a1-a14a-10b32e57fe82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
