<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Modificacin</name>
   <tag></tag>
   <elementGuidId>2206dc1c-9896-48f1-b130-7f66fa5518af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuModification > li.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuModification']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0500ae80-e2fe-47c4-a27e-4480d68e7344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>36b7b61b-c16c-483f-ba15-1ddce5e26d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificación</value>
      <webElementGuid>f42eec4b-6a30-41c5-a268-184bbef7845d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuModification&quot;)/li[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>0afa9c1c-8f02-44b8-9c20-5d45e49e0a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuModification']/li</value>
      <webElementGuid>85c13733-880e-4342-98f1-b67556e2ec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reclamos'])[1]/following::li[1]</value>
      <webElementGuid>ea462022-3ce3-41db-9a6c-b09feb607c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alertas y comentarios'])[1]/following::li[2]</value>
      <webElementGuid>dd55425e-edc5-4af4-9f4d-910a7f9eaebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operaciones masivas'])[1]/preceding::li[1]</value>
      <webElementGuid>7a748e2f-282d-41e1-b406-2a9bdd980386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/li</value>
      <webElementGuid>c1496f4b-4890-41c6-9e8a-90a6904ba538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Modificación' or . = 'Modificación')]</value>
      <webElementGuid>3f1fb5ad-ea70-4875-8bcb-766ae2e93387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
