<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Men (2)</name>
   <tag></tag>
   <elementGuidId>5e20f150-aae5-428b-8a11-afbb53f119dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebarCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebarCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>16212840-17af-4557-8567-11dae3dfaa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger</value>
      <webElementGuid>c39dd855-1010-4b17-812e-32b16c810ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebarCollapse</value>
      <webElementGuid>12d7b172-51fc-4941-84a0-217de12b7b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menú</value>
      <webElementGuid>998284e1-9e0c-4441-b631-001b4addd264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarCollapse&quot;)</value>
      <webElementGuid>6340f554-32e2-4e06-851f-1a9c0db1fb1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='sidebarCollapse']</value>
      <webElementGuid>d6ea7be2-8644-4e3a-a007-2e6d036d6556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuP']/app-menu/nav/ul/li</value>
      <webElementGuid>fdeaea88-f732-4226-8d7c-a33bf91e2426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/preceding::li[1]</value>
      <webElementGuid>d2e80eb5-3c81-419c-b274-ad7b3a45e84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>3cf4f210-9eba-4b67-b24b-e3d8f14644af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'sidebarCollapse' and (text() = 'Menú' or . = 'Menú')]</value>
      <webElementGuid>d79a132e-4074-4dd8-8991-587d59d163a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
