<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Men (4)</name>
   <tag></tag>
   <elementGuidId>8dd15b6d-c452-481e-977a-9695caf62392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebarCollapse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sidebarCollapse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c41b4f58-bf85-42cf-bafa-9be43bed3f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger</value>
      <webElementGuid>7aeb05c2-5ee0-4e05-81e7-b9b55e3c92a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebarCollapse</value>
      <webElementGuid>36cfe112-11aa-4c72-8304-a50fd2d35ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menú</value>
      <webElementGuid>ea838de9-8753-4d75-965b-12a51183e404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarCollapse&quot;)</value>
      <webElementGuid>82bf6731-86d9-47af-bd26-b4e507a3a0ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='sidebarCollapse']</value>
      <webElementGuid>977be623-7d2e-4bed-a906-a77874074cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuP']/app-menu/nav/ul/li</value>
      <webElementGuid>08f9a037-8a36-404c-a496-9f18c00736d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/preceding::li[1]</value>
      <webElementGuid>374bbace-3a2a-4259-8a9c-70672dc48d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>1a8d7c61-c5c4-47e5-a0cd-e498b3c86e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'sidebarCollapse' and (text() = 'Menú' or . = 'Menú')]</value>
      <webElementGuid>337a8aaf-551c-425c-be28-8854d7efd6f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
