<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Men</name>
   <tag></tag>
   <elementGuidId>d6e1bd20-65a7-4ccf-a5ca-acbcb5c7639b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebarCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebarCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>45660aa7-6d8f-48d4-a549-f36d02cf6180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger</value>
      <webElementGuid>1e766243-01bd-4633-a938-82f51a295ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebarCollapse</value>
      <webElementGuid>8ca18538-60fa-4a5e-b492-db86f7496d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menú</value>
      <webElementGuid>bc198d32-fafb-45ca-99eb-5e3e6fb3acdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarCollapse&quot;)</value>
      <webElementGuid>9c64fa22-6ed6-4856-96a0-9a16beb65fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='sidebarCollapse']</value>
      <webElementGuid>058aab4b-0bd0-4870-8e9b-3ab6bf889f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuP']/app-menu/nav/ul/li</value>
      <webElementGuid>a05142ed-6cd9-40ed-a42b-ac4fe83f8c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/preceding::li[1]</value>
      <webElementGuid>138fb7d1-e883-42d0-a41e-03167588fe5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>a333b44b-f63d-42b7-9dd2-e343d70ab5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'sidebarCollapse' and (text() = 'Menú' or . = 'Menú')]</value>
      <webElementGuid>af2794d7-11f8-45cd-aaab-2131a54f1439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
