<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mi Lista</name>
   <tag></tag>
   <elementGuidId>ef5a983c-911c-4b27-be06-dedd42ae146d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='miLista']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#miLista</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2c272c90-adb5-479b-a531-6dd2d4f69ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mi-lista liMiList active</value>
      <webElementGuid>82d22046-a2bf-4134-b321-503ec03bb295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>miLista</value>
      <webElementGuid>b8f922be-4d25-40cd-8225-4aaf69a6f2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mi Lista</value>
      <webElementGuid>a9daa466-ec98-46a3-a996-f87725ec2c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;miLista&quot;)</value>
      <webElementGuid>97a11397-25fc-46d1-9938-23e6a240441b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='miLista']</value>
      <webElementGuid>0d076f7f-2090-43fb-bda2-1d7947b6a174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista Común'])[1]/following::li[1]</value>
      <webElementGuid>77dab62c-f562-4e5e-9b3f-43ebc0616be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar Perfil:'])[1]/following::li[2]</value>
      <webElementGuid>e71de9d4-cf1c-457a-817a-480dd86d3045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulados'])[1]/preceding::li[1]</value>
      <webElementGuid>e2b99ffb-89f0-4a1a-ac4e-71ff765d253b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[2]</value>
      <webElementGuid>596f6df8-43f7-4b7d-a763-a7f3ccc07571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'miLista' and (text() = 'Mi Lista' or . = 'Mi Lista')]</value>
      <webElementGuid>643387f5-7dde-4e14-9c19-d30e12832a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
