<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Reclamos (2)</name>
   <tag></tag>
   <elementGuidId>a8dbcb18-8f79-4083-a8b2-4ab8f160547d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#disputeMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='disputeMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>949075e6-4de8-4c57-887d-f0f4c15276a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>disputeMenu</value>
      <webElementGuid>536f5bcc-b5f0-473c-a207-9c47dcf86bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>d8933347-65bb-46a1-a76c-2f5f66b8e0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reclamos</value>
      <webElementGuid>83925936-e639-4c77-8cc4-145505dd6b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disputeMenu&quot;)</value>
      <webElementGuid>78ef4d05-bf8d-48f2-afe6-eedb66f94e1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='disputeMenu']</value>
      <webElementGuid>f931a639-1dbd-44d3-b715-6a12e71cc876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuP']/app-menu/nav/ul/li[2]</value>
      <webElementGuid>a1089cc2-9905-4616-b532-24c776427918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alertas y comentarios'])[1]/following::li[1]</value>
      <webElementGuid>8f9c552b-c7a4-4179-8a94-a7b23db411fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/following::li[2]</value>
      <webElementGuid>803db6bd-efb6-42a2-9e17-bd9ba5275d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificación'])[1]/preceding::li[1]</value>
      <webElementGuid>e7ed5fcf-b94d-4ec9-86b3-c384444b23ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>6e9dbcb1-c982-409a-89ba-0e0d159c8939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'disputeMenu' and (text() = 'Reclamos' or . = 'Reclamos')]</value>
      <webElementGuid>8dd99144-7865-439f-a546-a7f83a9d0353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
