<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneCaso no aplica para proces_2d5db3</name>
   <tag></tag>
   <elementGuidId>aca1feaa-2ea5-4a5b-84ae-2c98b97e82fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#justificationActionFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justificationActionFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d793f6a2-dc0a-4032-b65e-5b77ff891c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>03a3ced4-28e5-4aae-9e1f-cca1eec8d999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>ffe2446e-4f7e-4f0b-bff3-b8ad48010137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justificationActionFormId</value>
      <webElementGuid>c696a4fd-6734-4a85-a78c-4d8bfe346fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>be00cc65-bbd1-4a4c-8326-fdacfb4695be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneCaso no aplica para proceso de modificaciónRequiere reasignación por cambio de usuarioSe reversa Proceso Usuario Analista no cuenta con acceso a NovedatSe desiste del proceso adelantado</value>
      <webElementGuid>3299f965-11dc-4125-beb1-4d0659d5daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justificationActionFormId&quot;)</value>
      <webElementGuid>04cfdf61-e970-4f76-8fb6-cc23cfcd667b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justificationActionFormId']</value>
      <webElementGuid>cba0e119-c536-459c-be45-f6567dd42bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>1301ea2e-2013-49fe-a8cb-fb6672ea5d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentario'])[1]/preceding::select[1]</value>
      <webElementGuid>7bb50e29-5d79-4757-bd3c-cf2613558869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::select[1]</value>
      <webElementGuid>ffe19dbd-3927-4aaf-9115-379bc23a1f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/select</value>
      <webElementGuid>789834ad-ceb4-4b54-91af-3e370480ebd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justificationActionFormId' and @name = 'justificationActionForm' and (text() = 'SeleccioneCaso no aplica para proceso de modificaciónRequiere reasignación por cambio de usuarioSe reversa Proceso Usuario Analista no cuenta con acceso a NovedatSe desiste del proceso adelantado' or . = 'SeleccioneCaso no aplica para proceso de modificaciónRequiere reasignación por cambio de usuarioSe reversa Proceso Usuario Analista no cuenta con acceso a NovedatSe desiste del proceso adelantado')]</value>
      <webElementGuid>a1a44f10-b284-4076-9faa-61632c5d1185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
