<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneInformacin cambio en actua_ce7fb1</name>
   <tag></tag>
   <elementGuidId>1635b912-365c-4b50-b354-4ffad354e13a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#justificationActionFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justificationActionFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f71a70e6-69c8-4b33-a243-1e8611d61945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>044c0950-49ac-4084-b11c-1dc1f4da16dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>4da28a26-9003-48e0-9684-f9ac94ce5567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justificationActionFormId</value>
      <webElementGuid>7c65bc9c-ff87-47f4-b930-f07f8e136b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>5c8e7bce-0491-403d-8477-a3eefb3b32d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneInformación cambio en actualización periodica solicitada por la entidadInformación ratificada no es procedente modificación en la informaciónSe aprueba proceso de acuerdo con las justificaciones autorizadas</value>
      <webElementGuid>0eba20d8-1c82-4780-b3d4-df6fe9c93c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justificationActionFormId&quot;)</value>
      <webElementGuid>04b0936f-5662-4720-8a7f-160506626f1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justificationActionFormId']</value>
      <webElementGuid>7b8bb1ae-3f18-4114-bfc2-faac15183026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>ef7a9abc-1977-4e95-875f-c69f71c07d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentario de desbloqueo'])[1]/preceding::select[1]</value>
      <webElementGuid>d0ab35af-4588-4012-9a21-cd3f23fd5d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>384f79fe-27fa-4c8b-b059-41b8fdfd678b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/select</value>
      <webElementGuid>2dc9f2bc-abde-41a9-9a39-50584a819aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justificationActionFormId' and @name = 'justificationActionForm' and (text() = 'SeleccioneInformación cambio en actualización periodica solicitada por la entidadInformación ratificada no es procedente modificación en la informaciónSe aprueba proceso de acuerdo con las justificaciones autorizadas' or . = 'SeleccioneInformación cambio en actualización periodica solicitada por la entidadInformación ratificada no es procedente modificación en la informaciónSe aprueba proceso de acuerdo con las justificaciones autorizadas')]</value>
      <webElementGuid>f2741ca3-f68b-4f8c-82b4-3b50df363cbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
