<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneDEVOLVERAPROBARDESASIGNARR_d86014</name>
   <tag></tag>
   <elementGuidId>5bc35a97-41e3-49a8-bb45-bbcd3281b32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionMassiveFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='actionMassiveFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7bb404c-fa67-4540-a9cb-6311f0e3b5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cf8326e4-f908-4bec-90bc-a3a61395cca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>actionMassiveForm</value>
      <webElementGuid>da3232ee-2699-44e9-9d1b-abb0be042ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionMassiveFormId</value>
      <webElementGuid>0dda4221-4d16-491c-ab72-651433c1a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionMassiveForm</value>
      <webElementGuid>68263197-621f-4282-b3c8-cb01fd1d2616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneDEVOLVERAPROBARDESASIGNARRATIFICAR Y APROBAR</value>
      <webElementGuid>7512eed9-322a-4f85-9375-689431ecca99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionMassiveFormId&quot;)</value>
      <webElementGuid>5cfb950e-87f2-4ff6-8b71-df915b5441c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='actionMassiveFormId']</value>
      <webElementGuid>0ede038b-9b7f-4046-8fdb-ed59376b8e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-5']/div/form/div/div/div/div[2]/div/select</value>
      <webElementGuid>66cd879f-815b-4519-9072-feefd62c34e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>e94e436b-881f-4021-a7b2-f2b6a194785a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>edf30fdd-79ef-473c-a228-2757c69107b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>ce6845ac-0407-4ab1-8599-c262e2d87afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>fb77b865-27e5-41c4-a017-0846a7c0ef88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'actionMassiveFormId' and @name = 'actionMassiveForm' and (text() = 'SeleccioneDEVOLVERAPROBARDESASIGNARRATIFICAR Y APROBAR' or . = 'SeleccioneDEVOLVERAPROBARDESASIGNARRATIFICAR Y APROBAR')]</value>
      <webElementGuid>fb2c892a-dd85-497f-9eba-db10e1f5b832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
