<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccionePENDIENTEPROCESANDOFINALIZ_809ca5</name>
   <tag></tag>
   <elementGuidId>358ed496-5ccb-4da6-8cdb-e21b365498c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='statesFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#statesFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ea84441-fc20-4a41-907b-9448d084096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>4fcfd93e-46f2-48db-8663-5f4f54196d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>statesForm</value>
      <webElementGuid>4a436cb6-e107-4c7b-82f4-8a27cd245d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statesFormId</value>
      <webElementGuid>1f5cf09e-0f57-4ae7-bb60-5c37cc6eb2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statesForm</value>
      <webElementGuid>053347b6-ca4a-44dc-83dd-5820e31626fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccionePENDIENTEPROCESANDOFINALIZADOERRORCARGANDOCARGADO</value>
      <webElementGuid>38ac1dd3-d525-473e-a644-0e40cb7b0b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statesFormId&quot;)</value>
      <webElementGuid>c85851cd-c8f2-4712-9a1a-513194945eaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='statesFormId']</value>
      <webElementGuid>cc9629e5-b494-4f87-97c8-6db5be9e30df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-6']/div/form/div/div/div/div[2]/div/select</value>
      <webElementGuid>36220721-1655-4072-a3f3-610739ec7588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::select[1]</value>
      <webElementGuid>09274013-0768-46ac-80db-c49e77d6dd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id Proceso'])[1]/following::select[1]</value>
      <webElementGuid>6006b6cd-5929-45ee-b16a-355735c55703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario Creación'])[1]/preceding::select[1]</value>
      <webElementGuid>ed645917-b70c-4827-8dad-d3fc395f95d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Desde'])[1]/preceding::select[1]</value>
      <webElementGuid>3b71e2c2-625b-460a-b749-bdbfacc1f1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>718cf44f-2bfd-4bf8-9492-9eb82001ef11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'statesFormId' and @name = 'statesForm' and (text() = 'SeleccionePENDIENTEPROCESANDOFINALIZADOERRORCARGANDOCARGADO' or . = 'SeleccionePENDIENTEPROCESANDOFINALIZADOERRORCARGANDOCARGADO')]</value>
      <webElementGuid>329a15dc-427a-48b0-bcfc-cdb36848bda3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
