<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneMODIFICACINRECLAMO</name>
   <tag></tag>
   <elementGuidId>39f1bf6c-2005-4720-85b7-fad91189e5de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typeProcessFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='typeProcessFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3710e4d6-9b5e-49ee-b345-d1ed5ce47b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3c8366d4-bb88-428c-8073-a3a855116a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>typeProcessForm</value>
      <webElementGuid>d6bfc4d4-609c-46f7-b9f2-ba50f01e5e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeProcessFormId</value>
      <webElementGuid>3e34e054-2d56-4589-a5ac-548a2c4f923f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeProcessForm</value>
      <webElementGuid>d6fedb03-c1be-4846-8bf3-bbb6b0f2db0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneMODIFICACIÓNRECLAMO</value>
      <webElementGuid>f7dd87d0-7506-430a-8584-995e5768e644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeProcessFormId&quot;)</value>
      <webElementGuid>d4c7abe0-6237-4581-ac9c-db499bd9a525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='typeProcessFormId']</value>
      <webElementGuid>381dda0b-4932-4cb8-b369-52bf77b54fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-4']/div/form/div/div/div/div/div/select</value>
      <webElementGuid>4a621976-d343-48a5-9d24-ba3f2bf5a51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>e1ddd1f1-3e2a-42e1-aa06-4826de5c386d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>690eed56-c2c8-4f00-a518-e99ab08eac16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>0a043602-c0dd-42e1-9f8a-76a33a16e630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>efb70cb3-937b-48a0-ae0d-5704a1e7b535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'typeProcessFormId' and @name = 'typeProcessForm' and (text() = 'SeleccioneMODIFICACIÓNRECLAMO' or . = 'SeleccioneMODIFICACIÓNRECLAMO')]</value>
      <webElementGuid>20798f37-7b05-4d1d-a0ef-688f3c5930a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
