<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneDerecho de PeticinTrmino d_6b3198</name>
   <tag></tag>
   <elementGuidId>0bda8f02-5c23-47f4-878e-b309457267ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justification']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#justification</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>14983987-2916-435a-b3db-79ec06ffb7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>adf38e42-5792-410b-b101-8ba73630f792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>9a65666f-915a-432c-a1fb-c6ea65f13073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>6903c396-0e85-40ed-b417-a548e7501fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneDerecho de PeticiónTérmino de Permanencia</value>
      <webElementGuid>4cde5f5d-68ca-4c22-a039-e1359e4468f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justification&quot;)</value>
      <webElementGuid>9e13bc1e-7c30-4073-84b6-06c5ef798811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justification']</value>
      <webElementGuid>4ff7e258-79a0-4a5e-a319-aad8abf99970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>854ed0da-df02-4be6-a473-ddeea7ac6ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>30e3e9bd-3771-492e-853d-95c1a8d5ba49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Model'])[1]/preceding::select[1]</value>
      <webElementGuid>779f51ae-2b62-4e11-8d3f-2ffee7de4603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[1]/preceding::select[1]</value>
      <webElementGuid>73cca4b3-103a-43db-9dfe-48bf25a5d8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>7c293f47-6418-4e48-bf3f-deca64032b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justification' and (text() = 'SeleccioneDerecho de PeticiónTérmino de Permanencia' or . = 'SeleccioneDerecho de PeticiónTérmino de Permanencia')]</value>
      <webElementGuid>d7c4fe6a-cdf6-4853-9cf4-e17e80d81810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
