<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione ACTUALIZAR LA INFORMACIN _308cb5 (1)</name>
   <tag></tag>
   <elementGuidId>eda63751-146d-4635-a97c-983b600e534d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='typeDisputeFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#typeDisputeFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56f074e6-474b-4c73-ae32-89b78caa314b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4d7cdf7d-c966-43b7-aaa9-b9d1dcf6d83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>typeDisputeForm</value>
      <webElementGuid>a83e2853-62bc-4a9a-a68f-a57c20c3196c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeDisputeFormId</value>
      <webElementGuid>3c65b9b3-f192-4dd0-a7ee-d319a7a1fa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeDisputeForm</value>
      <webElementGuid>242a807d-0f9d-4457-a916-05f103731b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN</value>
      <webElementGuid>37b4d2e0-f303-466e-9760-0f3bc2f8b062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeDisputeFormId&quot;)</value>
      <webElementGuid>42e076ba-c411-428d-8587-bcc8005b6220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='typeDisputeFormId']</value>
      <webElementGuid>f60ff299-a03a-4a07-ab54-650ec22a9f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>18b2465c-2124-4960-9472-067e71c813ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Reclamo'])[1]/following::select[1]</value>
      <webElementGuid>f6b4e925-15ef-4f96-a71a-6305a3f490ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Leyenda'])[1]/preceding::select[1]</value>
      <webElementGuid>2e4f7de1-f9e8-43b6-b011-56c1af08b5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>8e79ff14-b931-4c94-a538-df79b524da1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/select</value>
      <webElementGuid>838d0714-9ee1-4758-a299-c6efb57e54d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'typeDisputeFormId' and @name = 'typeDisputeForm' and (text() = 'Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN' or . = 'Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN')]</value>
      <webElementGuid>89c85699-0542-4bcb-99a9-3e1ff8adb650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
