<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneActualizacin en lneaManten_76b44e (2)</name>
   <tag></tag>
   <elementGuidId>1835339e-f8e0-43d4-86d6-70c721b74927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#justification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d3e292d1-3cc0-4411-9528-9e1909befe98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2a3c2e08-77c5-4371-8cc0-8fd813f44fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>bd628a30-6d73-4085-9b6c-b65c8f21fb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>744a2b95-8100-4221-b369-ab5af43945ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneActualización en líneaMantenimiento de informaciónSolicitud verificación del titularConfirmación de reporte</value>
      <webElementGuid>8b107baa-d6e6-4351-b7ba-8c7c91678dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justification&quot;)</value>
      <webElementGuid>8e68c7ae-04db-42a7-a6f4-743b3d703817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justification']</value>
      <webElementGuid>ea988649-1419-4cb4-a1c2-e4a6ff04638a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>4c298d7d-e051-434a-b427-7d599824db1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>6f90a3ca-b8c9-46fb-add0-d8bdc5efdb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Model'])[1]/preceding::select[1]</value>
      <webElementGuid>b020aa5c-78d8-4b60-b587-d8456c34e12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[1]/preceding::select[1]</value>
      <webElementGuid>9632ff6c-3d5d-45a2-9e87-126260ada911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>edae63be-18de-4baa-a359-79938f88af32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justification' and (text() = 'SeleccioneActualización en líneaMantenimiento de informaciónSolicitud verificación del titularConfirmación de reporte' or . = 'SeleccioneActualización en líneaMantenimiento de informaciónSolicitud verificación del titularConfirmación de reporte')]</value>
      <webElementGuid>788c60a3-b483-469a-96a3-73e0102b518c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
