<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneCorregido por Actualizacin_bd1ea0</name>
   <tag></tag>
   <elementGuidId>f089170d-a4d1-4381-9d4d-3ffc3225127b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterMassiveFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterMassiveFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b68d273-f42e-478c-af7a-de120b13a952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5729d6e0-b288-41bd-90db-27dcdf0da878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>33f4010c-fa25-42f0-9d5d-b7cb4da1d196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMassiveFormId</value>
      <webElementGuid>fd2f649b-e508-40d2-84aa-a0e32950284c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>50884ca7-06d1-4d25-8d48-40bdd55f9e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneCorregido por ActualizaciónBloquearRatificar</value>
      <webElementGuid>95e2c2aa-e44c-49c9-8f09-9a7e810a508a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMassiveFormId&quot;)</value>
      <webElementGuid>e3416dba-2bd7-4df2-a8e9-6c7f758ec552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterMassiveFormId']</value>
      <webElementGuid>e9cb623c-83aa-4d87-9739-6bf91e3b51bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-5']/div/form/div/div/div/div[3]/div/select</value>
      <webElementGuid>8c3e2368-b6ff-46d0-a4c9-5c1fa301d5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>481a032e-247f-4e72-890d-6188468cff37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>49e34539-d8ec-40dc-ad44-f80f3b5be965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>87dcc9fd-c6ab-4082-9e80-df553d3e31f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>0e143ae8-f3fd-4f59-871b-8ac913e95c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterMassiveFormId' and @name = 'filterMassiveForm' and (text() = 'SeleccioneCorregido por ActualizaciónBloquearRatificar' or . = 'SeleccioneCorregido por ActualizaciónBloquearRatificar')]</value>
      <webElementGuid>651f45d6-50cc-4870-8c9e-44dcc922bb29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
