<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneActualizacin en lneaManten_76b44e</name>
   <tag></tag>
   <elementGuidId>ef6cc2f3-f557-48a6-bda0-d0f989265939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#justification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>113216b8-1c11-49f4-ae75-b6c0f19631d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5f5c7b57-26dd-46c0-b2b5-36915e927c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>2dd9b034-d71d-4948-80f7-95c45279af2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>3e9a6904-5cd2-4a70-a69d-6d45f0339b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneActualización en líneaMantenimiento de informaciónSolicitud verificación del titularConfirmación de reporte</value>
      <webElementGuid>dd979304-3ed6-4d97-8e94-37289068b262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justification&quot;)</value>
      <webElementGuid>d50f99cb-c223-4325-be0c-9a1f6da85dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justification']</value>
      <webElementGuid>fb65e9b9-6796-48b3-acc5-db687867837d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>4f9e6dd4-d651-4b5b-8939-37608e67eeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>1e756a52-03eb-4981-8c05-1e1080a2e55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Model'])[1]/preceding::select[1]</value>
      <webElementGuid>049c182c-7acd-4316-9adb-7f7bb3422772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[1]/preceding::select[1]</value>
      <webElementGuid>b064f5ab-a92e-4b66-a580-07d6ea9af3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>7e44239d-353d-41cf-9353-006f9f0d0555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justification' and (text() = 'SeleccioneActualización en líneaMantenimiento de informaciónSolicitud verificación del titularConfirmación de reporte' or . = 'SeleccioneActualización en líneaMantenimiento de informaciónSolicitud verificación del titularConfirmación de reporte')]</value>
      <webElementGuid>8fbfe884-ce35-4661-b093-1aa3c8d29a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
