<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneCorregido por Actualizacin_2f6f5e</name>
   <tag></tag>
   <elementGuidId>6658ea2c-e342-4f74-81cd-63306f3a8d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterMassiveFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterMassiveFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f1a91117-5635-4f72-a5dd-8b94a7cd6d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d0b0b190-5b48-4870-ba8c-fa9f54d2872e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>92bf94ef-043f-4315-9900-8f62098454a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMassiveFormId</value>
      <webElementGuid>6eb8b3bc-9870-4e34-9c06-8cdfd1e862ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>08794a9c-2800-4557-be12-c1f8c4dcf69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneCorregido por ActualizaciónBloquearModificarDevolverSin Acción</value>
      <webElementGuid>f6ca0574-55b7-4d6e-bff6-5b6bb509dcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMassiveFormId&quot;)</value>
      <webElementGuid>f1667b24-02f1-435d-98f5-e11bf95ff285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterMassiveFormId']</value>
      <webElementGuid>656754d8-7b39-4ab9-af91-51a76cb5fa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-4']/div/form/div/div/div/div[3]/div/select</value>
      <webElementGuid>7fba0458-8b13-4f7a-8c25-5a18dadfdd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>83b2976f-7244-4d9c-8fa6-7fa298ef6f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>15f0efcc-262f-4ade-b458-9e0d988e9c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>4a76ca77-0cb8-4bfd-b628-721db7fbe568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>8ea7e367-f85d-4c69-92fd-190c231e3279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterMassiveFormId' and @name = 'filterMassiveForm' and (text() = 'SeleccioneCorregido por ActualizaciónBloquearModificarDevolverSin Acción' or . = 'SeleccioneCorregido por ActualizaciónBloquearModificarDevolverSin Acción')]</value>
      <webElementGuid>f8bbfea0-f2a9-414d-96ef-325f39de2eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
