<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneModificacinTipo de DocumentoOtros</name>
   <tag></tag>
   <elementGuidId>bdc59d4c-dc0f-4afb-9e63-c7c55d54f0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idFilter1Id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idFilter1Id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b08a2b84-84ec-4ac4-b2d8-b29a46126d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>899212b3-1ff8-437d-a2f2-aa130a3738fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filter1Form</value>
      <webElementGuid>3f357e75-fad3-434b-8ec5-4b1b01431b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idFilter1Id</value>
      <webElementGuid>b41e5176-e878-4910-b36c-293000ab98a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter1Form</value>
      <webElementGuid>bb2a688e-7b29-43f5-9e19-8c8ab7d4dfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneModificaciónTipo de DocumentoOtros</value>
      <webElementGuid>5e4b5470-0ec1-41ea-87ca-bbb2755bfd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idFilter1Id&quot;)</value>
      <webElementGuid>0d50630a-eb3d-4a94-b6cb-7ad3012d4f96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idFilter1Id']</value>
      <webElementGuid>670b4100-7f0c-48f8-b991-e1d05f0ea26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-5']/div/form/div/div/div[3]/div/div/select</value>
      <webElementGuid>9a63c7ef-11c0-45be-8509-9782f8403f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro 1'])[1]/following::select[1]</value>
      <webElementGuid>29393527-9eef-467f-9451-e44a1bc8914d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/following::select[1]</value>
      <webElementGuid>58ce3ab6-0d23-41a7-bb76-4550c4bd20b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::select[1]</value>
      <webElementGuid>0ca3ee06-e59c-4a02-8f8c-a195599de9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal Apply'])[1]/preceding::select[1]</value>
      <webElementGuid>b27aedfc-3040-4140-b0b8-00f64e037c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>4ffab6a8-ada3-4a5e-a04c-577d7890c1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idFilter1Id' and @name = 'filter1Form' and (text() = 'SeleccioneModificaciónTipo de DocumentoOtros' or . = 'SeleccioneModificaciónTipo de DocumentoOtros')]</value>
      <webElementGuid>86f7e430-51e9-4866-9e57-270056f6f01a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
