<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneCorregido por Actualizacin_80f12e</name>
   <tag></tag>
   <elementGuidId>d43eec0a-994e-4984-ac7e-0fc1202c1be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterMassiveFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterMassiveFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6b5048e-9d57-41eb-a65a-06c6a9de98dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9dc3cb40-7ee4-4299-8708-0e3a8593ac9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>21e46acc-c9be-4f28-9fb0-00e8b67613a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMassiveFormId</value>
      <webElementGuid>7fec3a1a-3cff-48e4-bf02-5928df22b0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>ed7d762d-2a1c-44a0-9277-58df70b6a860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneCorregido por ActualizaciónBloquearModificarRatificar</value>
      <webElementGuid>899e3bb4-a42b-412d-b4bf-a7ef431786f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMassiveFormId&quot;)</value>
      <webElementGuid>cf08be53-0dcb-4eb3-b38a-e8607d5be9aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterMassiveFormId']</value>
      <webElementGuid>a6a2113e-360c-439c-a428-e26014058613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-5']/div/form/div/div/div/div[3]/div/select</value>
      <webElementGuid>a3d74079-21be-460a-a573-14a4d62fd103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>34ce454d-c0e6-4c90-9a2e-61d4b636f54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>83517d45-9ab4-416f-83a9-019a63ff14eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>5fc5e049-a79c-4b92-bd01-cd2a4cdf93c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>e822bb82-14fb-4664-b706-72029164bf38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterMassiveFormId' and @name = 'filterMassiveForm' and (text() = 'SeleccioneCorregido por ActualizaciónBloquearModificarRatificar' or . = 'SeleccioneCorregido por ActualizaciónBloquearModificarRatificar')]</value>
      <webElementGuid>65275e04-0ba6-4eba-b289-ab7e74198c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
