<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneLa justificacin no concuer_da67dd</name>
   <tag></tag>
   <elementGuidId>69f360bc-5e50-4b74-b5aa-08055d4a5665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justificationActionFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#justificationActionFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3798baa1-e9fe-46d0-8677-09631ffe9ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cdc18c73-ebf9-4a88-b083-c23892441613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>8705ca79-294d-4d34-b2c0-5dd399dbf58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justificationActionFormId</value>
      <webElementGuid>48b51eee-4f54-48d7-a424-b512bd9a869e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>3b1cc906-294f-4b9b-9415-d49d2b8acd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneLa justificación no concuerda con el cambio realizado La fecha de pago no coincide con la solicitud de la EntidadSe eliminaron moras que no correspondenErrores del SistemaLa forma de pago indicada es erradaSe modificó la Obligación incorrectaLa modificación no se procesó correctamenteDevolución por aplicación Ley Habeas DataSe desiste de la modificaciónCambio de decisión en razón de la investigaciónInformación cambio en actualización periodica solicitada por la entidadAcción ejecutada no correspondiente a la decisión autorizadaYa existe reclamo sobre la obligaciónSe desiste del proceso adelantado</value>
      <webElementGuid>fb551b7e-61cf-4792-9155-b6e23ece6282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justificationActionFormId&quot;)</value>
      <webElementGuid>b934c574-cae4-4e26-9862-679c8b39d8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justificationActionFormId']</value>
      <webElementGuid>6a535f02-8610-4d69-b6ba-596486576b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>3fbe44ab-6226-41e4-be7e-9f8375a3e00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentario'])[1]/preceding::select[1]</value>
      <webElementGuid>842171e4-11b6-467e-91ae-28a053e2b2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::select[1]</value>
      <webElementGuid>d135d38b-6754-4b04-ac3b-f4aeac605f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/select</value>
      <webElementGuid>beb242be-8239-446d-b6af-e6cef390c54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justificationActionFormId' and @name = 'justificationActionForm' and (text() = 'SeleccioneLa justificación no concuerda con el cambio realizado La fecha de pago no coincide con la solicitud de la EntidadSe eliminaron moras que no correspondenErrores del SistemaLa forma de pago indicada es erradaSe modificó la Obligación incorrectaLa modificación no se procesó correctamenteDevolución por aplicación Ley Habeas DataSe desiste de la modificaciónCambio de decisión en razón de la investigaciónInformación cambio en actualización periodica solicitada por la entidadAcción ejecutada no correspondiente a la decisión autorizadaYa existe reclamo sobre la obligaciónSe desiste del proceso adelantado' or . = 'SeleccioneLa justificación no concuerda con el cambio realizado La fecha de pago no coincide con la solicitud de la EntidadSe eliminaron moras que no correspondenErrores del SistemaLa forma de pago indicada es erradaSe modificó la Obligación incorrectaLa modificación no se procesó correctamenteDevolución por aplicación Ley Habeas DataSe desiste de la modificaciónCambio de decisión en razón de la investigaciónInformación cambio en actualización periodica solicitada por la entidadAcción ejecutada no correspondiente a la decisión autorizadaYa existe reclamo sobre la obligaciónSe desiste del proceso adelantado')]</value>
      <webElementGuid>22b186c0-3112-454a-af09-e4a98d13ab76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
