<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneDerecho de PeticinTrmino d_6b3198 (1)</name>
   <tag></tag>
   <elementGuidId>613ca1ff-e883-40a4-9495-a7d62553ebf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justification']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#justification</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cc1113ff-6d0d-48c2-b8e8-7f5b1d63cf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>debe0ac3-9cde-475a-b7cf-d1aa94e4ed79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>b8427713-83d4-4389-b40b-b01d7e9c73db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>cbf3a799-0eb4-4ac5-b54b-24b9e62e360f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneDerecho de PeticiónTérmino de Permanencia</value>
      <webElementGuid>bd762730-932a-4800-b511-6e307b41a790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justification&quot;)</value>
      <webElementGuid>faed3ac7-a825-4cee-a19c-81bc9ab167d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justification']</value>
      <webElementGuid>31663190-839c-4e61-854f-6c2ce2ec00b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>aabfdfa0-5181-4d52-81d7-208fcfa41cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>8d635be4-0221-4fcd-a467-a8a5cceb6f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Model'])[1]/preceding::select[1]</value>
      <webElementGuid>764d032f-87bb-4e26-911b-73f780e72af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[1]/preceding::select[1]</value>
      <webElementGuid>0996cfe7-f184-4a56-9e2d-181cf8ad58ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>fc5b620b-e74e-418f-a504-c71041ac184b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justification' and (text() = 'SeleccioneDerecho de PeticiónTérmino de Permanencia' or . = 'SeleccioneDerecho de PeticiónTérmino de Permanencia')]</value>
      <webElementGuid>fcd7f30b-3a19-4e42-89c7-8f8c25f8ee87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
