<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneNmero de CasoNmero de Obli_97145b</name>
   <tag></tag>
   <elementGuidId>f28d8c2a-650a-47a1-b12d-0de20db3da93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idFilter2Id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idFilter2Id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6bbdbd98-1c86-4a54-a48b-e487c8a585ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3218af7c-3788-428c-937c-4d872ac77a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filter2Form</value>
      <webElementGuid>6080f914-9a58-4faf-9c5f-e8180c18b4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idFilter2Id</value>
      <webElementGuid>5d7572a0-0a2f-483b-a06e-6e76b9fe551b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter2Form</value>
      <webElementGuid>4c54438a-689a-4215-a247-cb473963ae45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneNúmero de CasoNúmero de ObligaciónTipo de Cartera</value>
      <webElementGuid>ba2aeca0-2a49-4437-88ee-7174d50df1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idFilter2Id&quot;)</value>
      <webElementGuid>28ba3b0e-4fce-4cb3-9d21-28f18bf1e1d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idFilter2Id']</value>
      <webElementGuid>c13376f8-e44a-449e-b0f0-bdf8f33e0581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-5']/div/form/div/div/div[3]/div[2]/div/select</value>
      <webElementGuid>c6ad5b36-7b1a-41e2-aa1d-d8da57aee333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro 2'])[1]/following::select[1]</value>
      <webElementGuid>aaad6bba-5b9e-4b73-bb3b-5771bcbbdb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro 1'])[1]/following::select[2]</value>
      <webElementGuid>cdb5f9ca-03ab-4e8d-bdd5-e1e1b6135e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::select[1]</value>
      <webElementGuid>2cb6842c-3509-48c3-9475-e857a7af07ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal Apply'])[1]/preceding::select[1]</value>
      <webElementGuid>77e939a6-4539-495d-bfa8-e553db63ae14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/select</value>
      <webElementGuid>226ccaad-8693-4c8e-b499-6532d2af9f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idFilter2Id' and @name = 'filter2Form' and (text() = 'SeleccioneNúmero de CasoNúmero de ObligaciónTipo de Cartera' or . = 'SeleccioneNúmero de CasoNúmero de ObligaciónTipo de Cartera')]</value>
      <webElementGuid>d9d50c5b-80d3-4784-b961-09b4abad255c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
