<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectMODIFICACINRECLAMO</name>
   <tag></tag>
   <elementGuidId>5327764e-8698-4c9a-8b24-89c717482d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='typeProcessFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#typeProcessFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a243e030-1087-44ba-991e-db6c70b7f901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>056dfb03-14ff-4211-86c3-e2eb11129daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>typeProcessForm</value>
      <webElementGuid>abacb34a-6151-475b-aa22-6f79b348141f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeProcessFormId</value>
      <webElementGuid>4ff766fb-3ab0-44fc-8ba0-12cc993392f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeProcessForm</value>
      <webElementGuid>b5e4f8db-39ce-4950-8629-1ada247b7461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectMODIFICACIÓNRECLAMO</value>
      <webElementGuid>add1d7b6-c71e-4227-8dd6-295804e768fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeProcessFormId&quot;)</value>
      <webElementGuid>e0c483f7-0e39-4284-a262-4936e241d610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='typeProcessFormId']</value>
      <webElementGuid>5f36dde2-941d-4ed2-a141-db294fd903fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-4']/div/form/div/div/div/div/div/select</value>
      <webElementGuid>fca84dd3-bd00-454f-8398-a038d5cdc057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>7a107ada-e6e9-4333-a543-f71c0d608f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>5e1b9a6b-2f6e-41fc-a6ee-5c41b615a610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>fef43825-c378-4efe-ad71-ae334a794447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7fe78e00-182f-4c9d-8098-5ef8fc154758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'typeProcessFormId' and @name = 'typeProcessForm' and (text() = 'SelectMODIFICACIÓNRECLAMO' or . = 'SelectMODIFICACIÓNRECLAMO')]</value>
      <webElementGuid>85f27484-d0d0-47d1-b322-9a5e2248c07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
