<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneSin Accin</name>
   <tag></tag>
   <elementGuidId>66766197-ce8f-46b9-bdb0-2db891d14a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterMassiveFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filterMassiveFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5f7519e-cbe2-4d65-8fc4-7b4a5cd58ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>757b081c-7c66-49ed-9758-6af87652585a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>12b94f79-573c-4d8f-b6fd-cb5e68a7af07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMassiveFormId</value>
      <webElementGuid>086cd14b-39ef-4423-b77f-d5c1a4093ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterMassiveForm</value>
      <webElementGuid>1808b04e-5e24-4853-83fc-a5070ce17ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneSin Acción</value>
      <webElementGuid>98fc6b1f-27a4-4378-979c-b5af74836016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMassiveFormId&quot;)</value>
      <webElementGuid>e7aee2b4-9ab1-4c6f-96ca-d42f301b3bf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterMassiveFormId']</value>
      <webElementGuid>bce7eea1-4b6d-4656-9adb-7dae1f5bacd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-5']/div/form/div/div/div/div[3]/div/select</value>
      <webElementGuid>6826716a-4366-42cb-bcff-79a5cc864f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>7e8ffda4-d7b9-4f87-872f-54add8463d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>ff91f3c9-c6c7-47cc-809a-7fd2a3d8df33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>5eb56997-c1f8-438f-bcb5-ced9d8d45e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>702222cd-591a-4bbd-a9b1-5c4f2634b54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterMassiveFormId' and @name = 'filterMassiveForm' and (text() = 'SeleccioneSin Acción' or . = 'SeleccioneSin Acción')]</value>
      <webElementGuid>cd102baa-f91b-40a1-ab11-6f76c34174eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
