<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneEl cambio propuesto no es _f5f283</name>
   <tag></tag>
   <elementGuidId>ddaf7c2c-f344-4c07-8189-beb522093e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justificationActionFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#justificationActionFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2e897229-cd99-47c6-93a9-33f02c5991fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>532711ec-e365-4beb-b519-b4c5290605cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>f837ebfc-4b1e-49ed-9825-fd020cce8333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justificationActionFormId</value>
      <webElementGuid>06e1c85e-c512-4033-907d-a1b6afdc83c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>897a1dd6-07b8-468b-b7df-7e3a603122a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneEl cambio propuesto no es correctoError en la selección de la obligaciónProceso no cumple con las condiciones requeridasRequiere reasignación por cambio de usuarioSe reversa Proceso Usuario Analista no cuenta con acceso a NovedatSe desiste del proceso adelantado</value>
      <webElementGuid>ff98639e-1bc8-4b6b-8313-11e4171e390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justificationActionFormId&quot;)</value>
      <webElementGuid>354ec1e9-84f9-489a-94d2-42ace5d9fcfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justificationActionFormId']</value>
      <webElementGuid>66565f71-0212-42b2-ba0b-a51246f24bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>5e8eeaf3-c71a-4c24-8437-f948ee5a8af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentario'])[1]/preceding::select[1]</value>
      <webElementGuid>fdf8aca2-95ea-4982-be7a-156654548c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::select[1]</value>
      <webElementGuid>5279db3c-fac4-4c27-9041-c722afc3d789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/select</value>
      <webElementGuid>7ca51e82-2e15-43b0-91df-ceea6610e11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justificationActionFormId' and @name = 'justificationActionForm' and (text() = 'SeleccioneEl cambio propuesto no es correctoError en la selección de la obligaciónProceso no cumple con las condiciones requeridasRequiere reasignación por cambio de usuarioSe reversa Proceso Usuario Analista no cuenta con acceso a NovedatSe desiste del proceso adelantado' or . = 'SeleccioneEl cambio propuesto no es correctoError en la selección de la obligaciónProceso no cumple con las condiciones requeridasRequiere reasignación por cambio de usuarioSe reversa Proceso Usuario Analista no cuenta con acceso a NovedatSe desiste del proceso adelantado')]</value>
      <webElementGuid>e515904f-bf4f-4ba8-b391-325fa983daad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
