<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione ACTUALIZAR LA INFORMACIN _308cb5 (2)</name>
   <tag></tag>
   <elementGuidId>b0a067e1-4cd6-4936-861d-bbb9e6a1c7d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typeDisputeFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='typeDisputeFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c067cdd-3417-4a97-bd0d-7d90173ddbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>eb5415ae-302a-4b1a-a73a-203ce8d6ea75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>typeDisputeForm</value>
      <webElementGuid>3f3e1e2a-7e98-420a-a279-6c082ef8dc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeDisputeFormId</value>
      <webElementGuid>c187fa8d-bb30-4e5e-821e-03c7fa800677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeDisputeForm</value>
      <webElementGuid>f45ab390-fba1-46f7-9ae0-ee42b4da98b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN</value>
      <webElementGuid>e12275f4-6e2c-47d5-a9fe-d2cc28b80e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeDisputeFormId&quot;)</value>
      <webElementGuid>5e322c70-9067-4512-b12b-564724920382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='typeDisputeFormId']</value>
      <webElementGuid>b19c6bc7-c38a-4d72-964f-1fdd5c374535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>1898e2f0-b973-4a66-b90f-dcf2f9dfb8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Reclamo'])[1]/following::select[1]</value>
      <webElementGuid>296dc4fb-292b-4449-86ee-f6b29a7ebcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Leyenda'])[1]/preceding::select[1]</value>
      <webElementGuid>7abf4976-7e86-4698-ab12-13dd2b0e9e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>d5af9d07-ddd1-41c7-b95b-d4ad8c46c0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/select</value>
      <webElementGuid>95748f13-e7e8-4592-a94b-a5f263d77078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'typeDisputeFormId' and @name = 'typeDisputeForm' and (text() = 'Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN' or . = 'Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN')]</value>
      <webElementGuid>c458fb77-7166-4dc5-9852-7bd87d650d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
