<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione ACTUALIZAR LA INFORMACIN _308cb5</name>
   <tag></tag>
   <elementGuidId>fcf16564-979a-4208-bae3-73d82923ee20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='typeDisputeFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#typeDisputeFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e2a4fa57-2bcd-415c-bf6f-0a4daaf18761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0b8b01ef-0562-437d-bcc1-dc5ba4e29d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>typeDisputeForm</value>
      <webElementGuid>57e0a915-cc99-4284-8497-d21c33b32885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeDisputeFormId</value>
      <webElementGuid>f8d0c658-b4eb-4d0d-b001-10e2d090de0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeDisputeForm</value>
      <webElementGuid>e435b963-8296-476f-a5c5-7603f5acbe5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN</value>
      <webElementGuid>ec742370-2c37-4a7f-8fb9-ca9a9f50a198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeDisputeFormId&quot;)</value>
      <webElementGuid>469b151e-27f6-45e2-8861-5f65fc78e452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='typeDisputeFormId']</value>
      <webElementGuid>116233a7-8ce7-40bd-8e9c-e82df7cf3df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>65f9726f-58b5-4a69-896b-abd53cd27b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Reclamo'])[1]/following::select[1]</value>
      <webElementGuid>b6b05d12-d0dc-49f9-87f3-bf5688754468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Leyenda'])[1]/preceding::select[1]</value>
      <webElementGuid>76476985-2c93-4b62-82b3-47d59eef2700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>c107e5d2-469a-4046-be49-5ac1268d135f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/select</value>
      <webElementGuid>49750c0d-9d59-433a-9554-81ab467a691f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'typeDisputeFormId' and @name = 'typeDisputeForm' and (text() = 'Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN' or . = 'Seleccione ACTUALIZAR LA INFORMACIÓN RECTIFICAR LA INFORMACIÓN CONOCER A LA INFORMACIÓN')]</value>
      <webElementGuid>ef74a221-ec24-4a56-ba2d-4f5082c48925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
