<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneAPROBARDEVOLVERDESASIGNAR</name>
   <tag></tag>
   <elementGuidId>3703c673-a357-4320-8cf3-2089abe305b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionMassiveFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='actionMassiveFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba53b7e1-a148-4149-888a-0cac8c2cc698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d7e897e2-22c5-4cda-92de-54b18d4b4cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>actionMassiveForm</value>
      <webElementGuid>cdb9d0e3-f713-4092-86be-d58a1ca9f965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionMassiveFormId</value>
      <webElementGuid>a18cdf08-ba19-4ece-8a92-9cbb89f5be59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionMassiveForm</value>
      <webElementGuid>e162dc73-c8c9-41a6-ba46-87e0c97b6b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneAPROBARDEVOLVERDESASIGNAR</value>
      <webElementGuid>0a6167dc-1e60-4b2b-9a66-13e307b76f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionMassiveFormId&quot;)</value>
      <webElementGuid>081bb010-5ea6-4292-8641-7fcd2e03194d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='actionMassiveFormId']</value>
      <webElementGuid>546c194d-1e8d-4fd8-a283-613448b653a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-4']/div/form/div/div/div/div[2]/div/select</value>
      <webElementGuid>27831a3c-dd68-46da-a90a-252cd91ed352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>684c6e29-877f-4e03-bc8a-c5a5bd8e0a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>01f9e2e6-10e9-47e3-9c9d-b8b0bfbca7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Fin Proceso'])[1]/preceding::select[1]</value>
      <webElementGuid>9935fee6-46c2-4dcf-af62-d6d7aa0f83e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b82d2039-75f9-459f-8530-f5955bf1b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'actionMassiveFormId' and @name = 'actionMassiveForm' and (text() = 'SeleccioneAPROBARDEVOLVERDESASIGNAR' or . = 'SeleccioneAPROBARDEVOLVERDESASIGNAR')]</value>
      <webElementGuid>565d971c-8925-4298-ab0a-e1fc5db37401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
