<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneError en la seleccin de la_d0e9d8</name>
   <tag></tag>
   <elementGuidId>ea7c8145-179c-472f-b227-14fd9bdd047f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justificationActionFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#justificationActionFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34ab0eb7-09d4-47ef-a460-e01a330c7dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>adbb7322-f46e-42ed-afe0-29635d7d8d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>606d2c5b-faaa-4250-ac28-3fc4020277e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justificationActionFormId</value>
      <webElementGuid>c5e4a7f7-2e59-4761-92d5-b587fd788763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>fe5a3d95-c637-4cf9-a58d-6a4e25507233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneError en la selección de la obligaciónCaso no aplica para proceso de modificaciónSe desiste del proceso adelantado</value>
      <webElementGuid>affa7d09-205d-4699-b640-281d12fd82f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justificationActionFormId&quot;)</value>
      <webElementGuid>4eb986db-d011-4ecf-925e-0e473128e05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justificationActionFormId']</value>
      <webElementGuid>f6dcd678-099c-4030-8840-d33d9e1ce077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>53a190bd-8a39-4908-a7ea-6572bbd2f814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentario'])[1]/preceding::select[1]</value>
      <webElementGuid>fbe33122-daf3-41a3-9d7b-7775e582c784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::select[1]</value>
      <webElementGuid>15608994-a0d6-406b-b959-52dc3f6a468a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/select</value>
      <webElementGuid>1a7341ae-e44c-471d-9023-1121bcff1e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justificationActionFormId' and @name = 'justificationActionForm' and (text() = 'SeleccioneError en la selección de la obligaciónCaso no aplica para proceso de modificaciónSe desiste del proceso adelantado' or . = 'SeleccioneError en la selección de la obligaciónCaso no aplica para proceso de modificaciónSe desiste del proceso adelantado')]</value>
      <webElementGuid>2072eafc-1fb9-4353-891e-695c8f2894ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
