<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneEl cambio propuesto no es _b80acb</name>
   <tag></tag>
   <elementGuidId>6f5aac92-b7ab-47a8-96b0-57ecb40b817f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#justificationActionFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justificationActionFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c2e898a-0e41-4bda-8f45-72a97bd3fbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>92e728b8-acb1-4bdf-b744-3d5270d61ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>78d533c7-6f28-4141-872c-8fadd78d373c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justificationActionFormId</value>
      <webElementGuid>d52d7abd-9948-44b3-8e03-3e8dfd5f5418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>justificationActionForm</value>
      <webElementGuid>6cf8ca83-bed8-4b91-a7e8-5ecb3044b598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneEl cambio propuesto no es correctoInformación cambio en actualización periodica solicitada por la entidadSe aprueba proceso de acuerdo con las justificaciones autorizadas</value>
      <webElementGuid>676821ce-0e06-4d86-beaf-dfd4401bfcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justificationActionFormId&quot;)</value>
      <webElementGuid>7c247d88-b408-4426-85be-fb6edbc90da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justificationActionFormId']</value>
      <webElementGuid>e5c01fe0-288f-480b-bd6d-126c9acb054d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>3fd4b554-ff5a-47a1-9629-53ad222823a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentario'])[1]/preceding::select[1]</value>
      <webElementGuid>3f7cf613-9821-4752-9677-9677c08bc2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::select[1]</value>
      <webElementGuid>f2d5c854-b281-47f6-be1c-d3ae28a33045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/select</value>
      <webElementGuid>d180f2e8-1df5-4123-a642-2d9f5ce34435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justificationActionFormId' and @name = 'justificationActionForm' and (text() = 'SeleccioneEl cambio propuesto no es correctoInformación cambio en actualización periodica solicitada por la entidadSe aprueba proceso de acuerdo con las justificaciones autorizadas' or . = 'SeleccioneEl cambio propuesto no es correctoInformación cambio en actualización periodica solicitada por la entidadSe aprueba proceso de acuerdo con las justificaciones autorizadas')]</value>
      <webElementGuid>ee25fa0e-2921-4f27-9659-acfb22255dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
