<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneDerecho de PeticinTrmino d_6b3198 (2)</name>
   <tag></tag>
   <elementGuidId>b3d92c17-8e59-4b3e-bffe-2299825262e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#justification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='justification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>39858f30-2517-43da-b7c3-1b99c7a06c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6490fac2-90f8-40ad-ada1-48375d4ed92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>7c015f33-3d2f-49a6-bea2-0acdf218e20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>justification</value>
      <webElementGuid>2119a1fd-1faf-4314-8ba9-84ffb1e9ef77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneDerecho de PeticiónTérmino de Permanencia</value>
      <webElementGuid>29246537-ec3b-4e82-a885-846687fb8a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justification&quot;)</value>
      <webElementGuid>5a2cdb5b-8c3b-424d-9636-b6018723127a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='justification']</value>
      <webElementGuid>8f572823-4483-4482-90be-8de208e97201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/app-form-holder-search/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>9b3516eb-29a9-4dd4-8f01-a1cc3c77ab08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>50bfcace-5a19-4718-a473-17ac0a132bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Model'])[1]/preceding::select[1]</value>
      <webElementGuid>989ec46f-7cc9-41fa-9082-cb5afcd7d56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Modal'])[1]/preceding::select[1]</value>
      <webElementGuid>8ba33253-f4ec-417e-a29b-104f8e772d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>108aca1d-5622-4f34-8afe-c62b261457cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'justification' and (text() = 'SeleccioneDerecho de PeticiónTérmino de Permanencia' or . = 'SeleccioneDerecho de PeticiónTérmino de Permanencia')]</value>
      <webElementGuid>6e37ae4b-196d-4470-a0d3-cf914c7cc541</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
