<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bloquear</name>
   <tag></tag>
   <elementGuidId>f9da41db-18fb-4350-9acc-72542c68618c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eliminar-radio-span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='eliminar-radio-span']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc7533ad-75d1-465b-871e-667e2aff3174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-text</value>
      <webElementGuid>006ccf11-450c-43bd-9519-d529c5668bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eliminar-radio-span</value>
      <webElementGuid>e4cd37ac-6e70-4c46-8bea-24f64515e5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bloquear</value>
      <webElementGuid>f76382a5-d9ae-4b1f-9495-be6f43a99f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eliminar-radio-span&quot;)</value>
      <webElementGuid>a1c6336c-424b-435b-87ea-78d37002f245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='eliminar-radio-span']</value>
      <webElementGuid>c1cc1533-5214-44c7-88d3-5c95a2621c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::span[1]</value>
      <webElementGuid>f7d4cc4d-d1f5-4fc9-99a2-7db63ec3e618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Case'])[1]/following::span[2]</value>
      <webElementGuid>7c5a8c5a-5e24-4035-ba50-d6d5a025ef15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corregido por Actualización'])[1]/preceding::span[1]</value>
      <webElementGuid>0a95b5fd-1972-4b08-824d-a935802d8405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[1]/preceding::span[2]</value>
      <webElementGuid>191a94d9-d6ae-4cac-bd00-ee6172bd246f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bloquear']/parent::*</value>
      <webElementGuid>b03a818f-9d67-43e5-8613-63ff967ac8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span</value>
      <webElementGuid>aaf5581a-2538-4fc5-b551-040df89de1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'eliminar-radio-span' and (text() = 'Bloquear' or . = 'Bloquear')]</value>
      <webElementGuid>7c32efbc-9fdc-4f0d-9002-764daecaffd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
