<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bloquear (1)</name>
   <tag></tag>
   <elementGuidId>a5f2360e-4487-4b31-9d30-6233273bb3b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eliminar-radio-span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='eliminar-radio-span']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8729f333-f21b-4ee7-8c89-f54f7f2e8df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-text</value>
      <webElementGuid>1b0967b4-7a5a-4989-91c9-286eb9355d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eliminar-radio-span</value>
      <webElementGuid>a49e2cd1-70bf-4cb8-b605-c56a65f40eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bloquear</value>
      <webElementGuid>4f809cf7-8c9f-4863-b26e-a89cc5113fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eliminar-radio-span&quot;)</value>
      <webElementGuid>ec86f317-86b3-4bda-a723-cfd2bc79110b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='eliminar-radio-span']</value>
      <webElementGuid>9fe5371c-3d31-44d9-9202-22f000d3e186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ratify'])[1]/following::span[1]</value>
      <webElementGuid>497e70d3-057b-4409-a783-0530865ff8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::span[2]</value>
      <webElementGuid>75784155-062d-4674-80c6-fc0bd3210795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corregido por Actualización'])[1]/preceding::span[1]</value>
      <webElementGuid>08734bb4-4391-4a6e-8509-607e7eccfd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[1]/preceding::span[2]</value>
      <webElementGuid>8f3d8364-3455-475e-8e6f-74061108c3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bloquear']/parent::*</value>
      <webElementGuid>9c2774e4-3e3e-4cb0-83b3-df3fe426a1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span</value>
      <webElementGuid>e825ecf2-dc44-4c31-86a3-8e9fd6dd0459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'eliminar-radio-span' and (text() = 'Bloquear' or . = 'Bloquear')]</value>
      <webElementGuid>1bd3927e-00c6-4552-ab10-dc34f3f92c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
