<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ratify</name>
   <tag></tag>
   <elementGuidId>911c5807-dcc8-4865-a30b-c457f3fb2a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ratificar-radio-span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ratificar-radio-span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d34fe241-bd44-4d40-966f-589d0e736e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-text</value>
      <webElementGuid>6673b410-e8cb-4723-9410-203f5869993a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ratificar-radio-span</value>
      <webElementGuid>8958a7d2-d1e0-46a8-8267-9a8c61e3eb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ratify</value>
      <webElementGuid>abe25981-0c47-458b-953a-830d27bd2f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ratificar-radio-span&quot;)</value>
      <webElementGuid>efd9be67-885e-4775-a7c5-4e00558b3425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ratificar-radio-span']</value>
      <webElementGuid>e2327cbe-d84a-43f4-8afe-c8ba1bc9781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::span[1]</value>
      <webElementGuid>c46d4d91-43b5-425c-bc4d-0eff2b721e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBM 000000138728197389 BANCOLOMBIA'])[1]/following::span[2]</value>
      <webElementGuid>096e6582-389b-43cd-a60b-78f890129328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bloquear'])[1]/preceding::span[1]</value>
      <webElementGuid>f76493f9-ff3a-4909-89eb-cb3ba66770bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corregido por Actualización'])[1]/preceding::span[2]</value>
      <webElementGuid>f62178f3-c73d-43c1-a547-8c5873cefc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ratify']/parent::*</value>
      <webElementGuid>00163f27-8566-4367-bdfc-712b472bfc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span</value>
      <webElementGuid>287388d4-826f-4577-baac-d311d891b879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ratificar-radio-span' and (text() = 'Ratify' or . = 'Ratify')]</value>
      <webElementGuid>a95d8337-7f77-48de-ba7f-8da86b050a67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
