<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__momentKnowInfoForm (2)</name>
   <tag></tag>
   <elementGuidId>aa3bdd8d-77e1-4a7e-86c2-7520a2039134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#momentKnowInfoFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='momentKnowInfoFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>92c2ddca-6ac0-4b39-b51d-c6d3e31c847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>52e8b1b3-b7c5-4eb7-984c-4e19db287d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>momentKnowInfoForm</value>
      <webElementGuid>05340be1-1133-4e0d-ba85-b6be9cab0f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>momentKnowInfoFormId</value>
      <webElementGuid>790e474e-e4b3-4e7d-a21f-a29947c02364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>9625e1d7-1292-4383-98fe-b72a3c7382a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>momentKnowInfoForm</value>
      <webElementGuid>02b01eb9-b8f2-480b-8fa0-2d328f7dc17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4a0caf4c-3e2e-4a2e-89cf-91859ef78adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;momentKnowInfoFormId&quot;)</value>
      <webElementGuid>ebc26732-17db-451a-89cf-d5fd4e047517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='momentKnowInfoFormId']</value>
      <webElementGuid>55e1e5b6-6019-4f7d-a1fe-288dd8c2dd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0123c25c-eebb-4569-95b6-66f1081f557c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'momentKnowInfoFormId' and @name = 'momentKnowInfoForm']</value>
      <webElementGuid>3fa664b2-26d8-4299-be70-cc810f949063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
