<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__momentKnowInfoForm (1)</name>
   <tag></tag>
   <elementGuidId>087999ad-6edf-45d4-9c8e-942f1dec266b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='momentKnowInfoFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#momentKnowInfoFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cd811c01-f845-4aee-8bf5-029f7098e447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>ed5a446e-3343-4063-b274-f074f01c7806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>momentKnowInfoForm</value>
      <webElementGuid>da44690c-1679-4667-81e5-80c5c47ef5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>momentKnowInfoFormId</value>
      <webElementGuid>49a14f95-6f2b-4dc6-9fa1-3c7d5e27dc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>752036f4-8355-4bcd-969f-d84709474547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>momentKnowInfoForm</value>
      <webElementGuid>6476cba8-5f58-4a32-b79d-1a536fd28aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>accc5a19-6f33-474c-a4e9-5f8e9e93e962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;momentKnowInfoFormId&quot;)</value>
      <webElementGuid>d69845a5-b625-46ce-80dd-118f4528b35b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='momentKnowInfoFormId']</value>
      <webElementGuid>9252a0a0-4902-487f-9e5d-13a2a8dc0c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6e5c7514-cd1b-4a6d-b262-5324ba5b13c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'momentKnowInfoFormId' and @name = 'momentKnowInfoForm']</value>
      <webElementGuid>7c4b3fa2-2b95-4c94-881b-b138fad852cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
