<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GET_XPM Copy</name>
   <tag></tag>
   <elementGuidId>38d2b6ff-7854-4424-b8ae-baee6645b442</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;inquirer\&quot;: {\n        \&quot;userIdType\&quot;: \&quot;4\&quot;,\n        \&quot;userIdNumber\&quot;: \&quot;715736\&quot;,\n        \&quot;counterpartyIdType\&quot;: \&quot;1\&quot;,\n        \&quot;counterpartyIdNumber\&quot;: \&quot;900422614\&quot;\n    },\n    \&quot;identifyingAttributes\&quot;: {\n        \&quot;personIdType\&quot;: \&quot;4\&quot;,\n        \&quot;personIdNumber\&quot;: \&quot;715736\&quot;,\n        \&quot;lastName\&quot;: \&quot;SEGURA\&quot;\n    },\n    \&quot;behaviour\&quot;: {\n        \&quot;appClientType\&quot;: \&quot;service\&quot;,\n        \&quot;tecMarking\&quot;: \&quot;false\&quot;,\n        \&quot;attachPin\&quot;: true,\n        \&quot;capture\&quot;: false\n    },\n    \&quot;auditLog\&quot;: {                                                       \n        \&quot;transactionId\&quot;: \&quot;12345678912365478\&quot;,\n        \&quot;dataSource\&quot;: \&quot;Any\&quot;,\n        \&quot;requestTimestamp\&quot;: 1551916813854\n    },\n    \&quot;dataRequested\&quot;: \&quot;{\\\&quot;bestName\\\&quot;:\\\&quot;bestName\\\&quot;}\&quot;\n}\n&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>d0d3d97c-88fd-499f-ad0f-437009c0160f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>access_token</name>
      <type>Main</type>
      <value>eyJraWQiOiJ2M1FSYXBWY2l6S282WnJ5SVozQjZIb1VDQnUzWnB4S3lrR1ZqRV9CeXhVIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjE1emJIbm4xWmJ6Y0RLanJCZE45bkYxN3YxUkRqeTdMd0hIa2lCSUx1VlEiLCJpc3MiOiJodHRwczovL2V4cGVyaWFuLWxhdGFtYi5va3RhcHJldmlldy5jb20vb2F1dGgyL2F1c2Rid2k3cGVzNzFuMGhVMGg3IiwiYXVkIjoiaHR0cHM6Ly93d3cuZGF0YWNyZWRpdG8uY29tLmNvL2NsaWVudHMiLCJpYXQiOjE1OTMwMzg4MzEsImV4cCI6MTU5MzA1MzIzMSwiY2lkIjoiMG9hb3k4NHpnZndtQlFQRlIwaDciLCJ1aWQiOiIwMHVveTlzeWQ0YnE0ajF6RzBoNyIsInNjcCI6WyJleHBjb19xdWV1ZV9tYW5hZ2VyX3NlcnZpY2UiXSwic3ViIjoiMi05MDA0MjI2MTQuMTUxQGRldi5kYXRhY3JlZGl0by5jb20uY28iLCJleHBjb19iYXNlX2VtYWlsIjoiZ2FicmllbC52ZWdhc0BleHBlcmlhbi5jb20iLCJleHBjb19iYXNlX2xhc3ROYW1lIjoiQXBsaWNhdGlvbihkZXYpIiwiZXhwY29fYmFzZV9pZFR5cGUiOiIyIiwiZXhwY29fYmFzZV9maXJzdE5hbWUiOiJOb3ZlZGF0IENvcmUiLCJleHBjb19hdXRoel9xdWV1ZV9tYW5hZ2VyX3NlcnZpY2UiOiJ7XCJpZFwiOlwiMjIwXCIsXCJuYW1lXCI6XCJRdWV1ZSBNYW5hZ2VyXCIsXCJjdXN0b21lcnNcIjpbe1wiaWRUeXBlXCI6XCIyXCIsXCJpZFwiOlwiOTAwNDIyNjE0XCIsXCJsZWdhbE5hbWVcIjpcIkVYUEVSSUFOIENPTE9NQklBIFMuQS5cIixcInVzZXJNYWlsXCI6XCJnYWJyaWVsLnZlZ2FzQGV4cGVyaWFuLmNvbVwiLFwidXNlckNpdHlcIjpcIi0tLS0tLVwiLFwidXNlck9mZmljZVwiOlwiRXhwZXJpYW5cIixcInByb2ZpbGVzXCI6W3tcImlkXCI6XCIzNDUyXCIsXCJuYW1lXCI6XCJTZXJ2aWNpbyAtIFF1ZXVlIE1hbmFnZXJcIixcImlkUGVyZmlsQXBwXCI6XCIzNDEyXCIsXCJjb25maWd1cmF0aW9uXCI6e1wic2VydmljZXNcIjpbXCJzeW5jTWVzc2FnZVwiXX19XX1dfSIsImV4cGNvX2Jhc2VfbG9naW4iOiIyLTkwMDQyMjYxNC4xNTFAZGV2LmRhdGFjcmVkaXRvLmNvbS5jbyIsImV4cGNvX2Jhc2VfYXBpVXNlciI6dHJ1ZSwiZXhwY29fYmFzZV9pZE51bWJlciI6IjkwMDQyMjYxNCIsImV4cGNvX2Jhc2Vfc2Vjb25kRW1haWwiOiJlZGlzc29uLnZhcmdhc0BleHBlcmlhbi5jb20ifQ.TRCaHdkXp8iN1lzdjwKhn9nwrXbqqPFCurLD0UpGWp7VnptbewxOI8dfJ8-fWzs38tFXJgewHzSesG02bJs6F6w2S2172-TqmYbvlWfDcAOWiOKNCAkjpQIAqUd_9IFtZt526ejsWyHCRH8mnjB2qd80hSPGF8t59aYjqM7s1j1Dk8-6t6nfpfDK0xMVT-7CuocGsuk8KYISto_10PFRC3JlrGEsg2YkPMYy0JcDh5XmuU74UgaEz2c_lokO7mPfhF91UDLnTpxfZhVds15dRPHhRGB9GR4awjg3Ju1lHVcSSzwNJ5FXj2o4TtloFQ8H9IYWpZLFuhyT2klVi67cdw</value>
      <webElementGuid>ec7cfc90-93e5-4708-8ebd-1961ea907e50</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-Experian-SLA-Env</name>
      <type>Main</type>
      <value>qa5</value>
      <webElementGuid>705f2d5f-2887-4a33-86d9-4db456fb9fbb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client_secret</name>
      <type>Main</type>
      <value>slfYbyiQdAAVxXGpCJnS2HpJMP4sSISli5lI5rwc</value>
      <webElementGuid>4dfea1cc-9516-459b-99c3-963acd8e1cfc</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client_id</name>
      <type>Main</type>
      <value>0oap0nck68163Jp7r0h7</value>
      <webElementGuid>2958b549-ef94-48c5-92b7-193236fc690e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.3.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://10.54.16.33:444/cs/data/v1/bureau/person/pin/744947</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
