<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request</name>
   <tag></tag>
   <elementGuidId>28b7fb39-5066-48fc-b4f7-1b5c7de310ab</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>c67bcaa9-6677-4988-8a72-046af6ac232c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Host</name>
      <type>Main</type>
      <value>experian-latamb.oktapreview.com</value>
      <webElementGuid>b8ebe4f5-3fb3-47d9-a971-57aafae32878</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/x-www-form-urlencoded</value>
      <webElementGuid>a2afd4df-8ebb-47e7-a9df-e81d841d45ec</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>grant_type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d3442574-a8c9-4a10-80be-5107e065f06e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>username</name>
      <type>Main</type>
      <value>2-900422614.151@dev.datacredito.com.co</value>
      <webElementGuid>ec6af795-5539-4451-94b0-648fdcaa2be7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>3xpNDtD3v-2019</value>
      <webElementGuid>073ed94e-cb6c-45a8-b682-75b9dc2a5cdf</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client_id</name>
      <type>Main</type>
      <value>0oaoy84zgfwmBQPFR0h7</value>
      <webElementGuid>8cbfb7b2-abdd-4c5f-99f9-ec159fd100d3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client_secret</name>
      <type>Main</type>
      <value>XFKqQ4dD04RjJ6fKoSwCD9u-3OKC_ay43EvF2S1K</value>
      <webElementGuid>cb650e04-db6a-49b8-a5ce-eabef4f15369</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>expco_queue_manager_service expco_novedat_core_service</value>
      <webElementGuid>b7e025db-bab2-48eb-98f9-0dbc1f1f08bf</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Cookie</name>
      <type>Main</type>
      <value>JSESSIONID=6BFE84EC917C7606DE80A000DC68E4BE</value>
      <webElementGuid>cc678f49-3fca-4bbe-8fb5-fbb1fca294bb</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.3.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://qa-iservicesesb.datacredito.com.co:444/oauth2/ausdbwi7pes71n0hU0h7/v1/token?grant_type=password&amp;username=2-900422614.151@qa.datacredito.com.co&amp;password=3xpNDtQ4-2019&amp;client_id=0oaoy8cmusl96bWTb0h7&amp;client_secret=RMeWkk3TMI1UIzT2FaP6DJgsS3NZ70kyvojbWo02&amp;scope=expco_queue_manager_service</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
