<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>SERVICIO IDENTITY Copy</name>
   <tag></tag>
   <elementGuidId>ea12c9b3-f1d1-4f1d-a637-64cce34989c3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n\t\&quot;inquirer\&quot;: {\r\n\t\t\&quot;userIdType\&quot;: \&quot;715736\&quot;,\r\n\t\t\&quot;userIdNumber\&quot;: \&quot;4\&quot;,\r\n\t\t\&quot;counterpartyIdType\&quot;: \&quot;2\&quot;,\r\n\t\t\&quot;counterpartyIdNumber\&quot;: \&quot;900422614\&quot;\r\n\t},\r\n\t\&quot;identifyingAttributes\&quot;: {\r\n\t\t\&quot;personIdType\&quot;: \&quot;1\&quot;,\r\n\t\t\&quot;personIdNumber\&quot;: \&quot;79628749\&quot;\r\n\t},\r\n\t\&quot;dataRequested\&quot;: \&quot;pinScore\&quot;,\r\n\t\&quot;behaviour\&quot;: {\r\n\t\t\&quot;candidates\&quot;: -1,\r\n\t\t\&quot;multiple\&quot;: true\r\n\t}\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>d7aa23ac-b278-492c-ba0d-cd5edfd57bd0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>access_token</name>
      <type>Main</type>
      <value>eyJraWQiOiJ2M1FSYXBWY2l6S282WnJ5SVozQjZIb1VDQnUzWnB4S3lrR1ZqRV9CeXhVIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULi0wajRQMXpxc05IbU5DVlhJMlY4OU9NVDBtbkRkR21DaTRoRHI2SEFwVGMiLCJpc3MiOiJodHRwczovL2V4cGVyaWFuLWxhdGFtYi5va3RhcHJldmlldy5jb20vb2F1dGgyL2F1c2Rid2k3cGVzNzFuMGhVMGg3IiwiYXVkIjoiaHR0cHM6Ly93d3cuZGF0YWNyZWRpdG8uY29tLmNvL2NsaWVudHMiLCJpYXQiOjE1OTI0NTMyNDgsImV4cCI6MTU5MjQ4MjA0OCwiY2lkIjoiMG9hb3k4NHpnZndtQlFQRlIwaDciLCJ1aWQiOiIwMHVveTlzeWQ0YnE0ajF6RzBoNyIsInNjcCI6WyJleHBjb19xdWV1ZV9tYW5hZ2VyX3NlcnZpY2UiXSwic3ViIjoiMi05MDA0MjI2MTQuMTUxQGRldi5kYXRhY3JlZGl0by5jb20uY28iLCJleHBjb19iYXNlX2VtYWlsIjoiZ2FicmllbC52ZWdhc0BleHBlcmlhbi5jb20iLCJleHBjb19iYXNlX2xhc3ROYW1lIjoiQXBsaWNhdGlvbihkZXYpIiwiZXhwY29fYmFzZV9pZFR5cGUiOiIyIiwiZXhwY29fYmFzZV9maXJzdE5hbWUiOiJOb3ZlZGF0IENvcmUiLCJleHBjb19hdXRoel9xdWV1ZV9tYW5hZ2VyX3NlcnZpY2UiOiJ7XCJpZFwiOlwiMjIwXCIsXCJuYW1lXCI6XCJRdWV1ZSBNYW5hZ2VyXCIsXCJjdXN0b21lcnNcIjpbe1wiaWRUeXBlXCI6XCIyXCIsXCJpZFwiOlwiOTAwNDIyNjE0XCIsXCJsZWdhbE5hbWVcIjpcIkVYUEVSSUFOIENPTE9NQklBIFMuQS5cIixcInVzZXJNYWlsXCI6XCJnYWJyaWVsLnZlZ2FzQGV4cGVyaWFuLmNvbVwiLFwidXNlckNpdHlcIjpcIi0tLS0tLVwiLFwidXNlck9mZmljZVwiOlwiRXhwZXJpYW5cIixcInByb2ZpbGVzXCI6W3tcImlkXCI6XCIzNDUyXCIsXCJuYW1lXCI6XCJTZXJ2aWNpbyAtIFF1ZXVlIE1hbmFnZXJcIixcImlkUGVyZmlsQXBwXCI6XCIzNDEyXCIsXCJjb25maWd1cmF0aW9uXCI6e1wic2VydmljZXNcIjpbXCJzeW5jTWVzc2FnZVwiXX19XX1dfSIsImV4cGNvX2Jhc2VfbG9naW4iOiIyLTkwMDQyMjYxNC4xNTFAZGV2LmRhdGFjcmVkaXRvLmNvbS5jbyIsImV4cGNvX2Jhc2VfYXBpVXNlciI6dHJ1ZSwiZXhwY29fYmFzZV9pZE51bWJlciI6IjkwMDQyMjYxNCIsImV4cGNvX2Jhc2Vfc2Vjb25kRW1haWwiOiJlZGlzc29uLnZhcmdhc0BleHBlcmlhbi5jb20ifQ.CU1_pEMlkPLLNSCsJClYQsrOEN3liX2FmzhWo2g6KH2BBXHdhUBovjmRQ5dNd-bq6Z84DU7pR78-OcSKy3M01n7j94cWL37aPDznQDp8J_L2PQKYv0OqxPCv2YmYddRq9kIToclJ5DQL6ZSvBAPvMcSaB7LfydI9DxZJoiSGQNu61LnQjNgwwYK1l4OtLqsFfT6sx9F62LEBQ3u9urTesyvSxtEBIEObTH1hoA8rs_lCAa4fXPhca94vGTURhaK85n6qClrX5UhIt5J96x46PB6YhFAyh0pzE-gjzlAEoYllJGjPSZZsjb8CqwtEfBnS1y1Y6pCIkDMRkr1TFIpodg</value>
      <webElementGuid>34cc7350-c6a1-4a01-bb6a-feb8cbaf8114</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-Experian-SLA-Env</name>
      <type>Main</type>
      <value>qa5</value>
      <webElementGuid>0d4637e2-1606-4b0c-9dc1-8689119bfd51</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client_secret</name>
      <type>Main</type>
      <value>slfYbyiQdAAVxXGpCJnS2HpJMP4sSISli5lI5rwc</value>
      <webElementGuid>bba644fe-f342-45c9-8847-fed5303547f1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client_id</name>
      <type>Main</type>
      <value>0oap0nck68163Jp7r0h7</value>
      <webElementGuid>51c246ca-19f2-4d35-9e33-a614acd6a27c</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.3.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://10.54.16.33:444/cs/data/v1/bureau/person/identity</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
