<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmar Correo electrnico_reemailDi_160b6f</name>
   <tag></tag>
   <elementGuidId>de2468c5-31f3-47ac-962c-ea001ce96b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reemailDisputeform']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reemailDisputeform</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76d2cd6c-f77c-4b51-abe4-945c3c43ae94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-star-inserted ng-dirty ng-invalid</value>
      <webElementGuid>4d789f96-ea47-4cee-b18c-a0f95da618d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reemailDisputeform</value>
      <webElementGuid>b0e85748-f77e-418c-8ac1-2fc56e85d6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>ca4055bd-5a00-4520-9aa2-9cdb0f0c23a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reemailDisputeform</value>
      <webElementGuid>c33a5dd4-b0a8-4edb-bcd8-fe987b7d0b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca9c296e-a97a-4c7c-885e-f60226ad9227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reemailDisputeform&quot;)</value>
      <webElementGuid>57df22ec-abb7-433f-8374-a583b31b0e44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reemailDisputeform']</value>
      <webElementGuid>7a279c67-98d7-4c9c-8f6d-597ac1960f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div/div[2]/input</value>
      <webElementGuid>7e7e8ef9-4c67-40ab-9db1-46e6cda02750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2d59480f-447b-4d36-b01d-3bba46629287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reemailDisputeform' and @name = 'reemailDisputeform' and @type = 'text']</value>
      <webElementGuid>8883a106-b14b-4dd9-b10f-d1c0e4526bf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
