<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Acepto recibir respuestas de este rec_83a274</name>
   <tag></tag>
   <elementGuidId>6164b027-5a07-4709-b24e-b57a9c9b478d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2c3aa088-a4c9-4d02-b9cc-a3bcf71b7fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkConditions</value>
      <webElementGuid>136dc585-e4f3-4352-978b-a979f5c2086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>acceptAnswer</value>
      <webElementGuid>26b66fbf-769f-4d76-bfdb-54afe049bac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acepto recibir respuestas de este reclamo a través de mi correo electrónico*</value>
      <webElementGuid>ee26cbcf-117b-4c53-b15d-a3202a0db270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/article[@class=&quot;main-content&quot;]/app-formulation-dispute[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/section[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/section[@class=&quot;select-action typeLetterBody ng-star-inserted&quot;]/div[@class=&quot;page-card&quot;]/div[@class=&quot;acc-info&quot;]/div[@class=&quot;checkbox-container&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;checkConditions&quot;]</value>
      <webElementGuid>e1c02bf8-f037-4794-93e3-52aecd6724de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::label[1]</value>
      <webElementGuid>0531723c-0365-4262-8c5c-45d00b50250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política de Tratamiento de Datos.pdf'])[1]/preceding::label[1]</value>
      <webElementGuid>a3295e3d-4a06-43be-b548-f6edf581eecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acepto recibir respuestas de este reclamo a través de mi correo electrónico']/parent::*</value>
      <webElementGuid>62be445c-ed74-4fd5-b2a1-75a52a97e4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>dc52cd5c-cf11-4797-947f-0f519e421bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Acepto recibir respuestas de este reclamo a través de mi correo electrónico*' or . = 'Acepto recibir respuestas de este reclamo a través de mi correo electrónico*')]</value>
      <webElementGuid>a9c809e7-6533-4b71-802d-24280e3aa62f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
