<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__momentKnowInfoForm</name>
   <tag></tag>
   <elementGuidId>a98ab3f0-22d5-4864-9a6f-59f0a4d9b17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='momentKnowInfoFormId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#momentKnowInfoFormId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b1be7c2b-bad1-423c-983c-a8b878fe1a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>c3a1bcdc-ca98-46f3-aea3-52b85e0f7c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>momentKnowInfoForm</value>
      <webElementGuid>c99e961e-0dee-4335-85ae-db2bb278499e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>momentKnowInfoFormId</value>
      <webElementGuid>94c96333-129c-497f-a12b-72cfdcd11328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>50e50853-9a94-495a-8e11-23d637231d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>momentKnowInfoForm</value>
      <webElementGuid>f9af9d45-eee4-4e41-b8cd-16264445f9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f3e75374-7a56-4b3e-9aee-f40ad6a92614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;momentKnowInfoFormId&quot;)</value>
      <webElementGuid>f584cf89-463d-4c9e-a524-82197d5f5255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='momentKnowInfoFormId']</value>
      <webElementGuid>2f926b0c-ffdb-4a3d-956a-6fe579a8fe58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>93818763-b76d-41ce-b10d-db81eb092814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'momentKnowInfoFormId' and @name = 'momentKnowInfoForm']</value>
      <webElementGuid>eefa1318-6b99-4d46-95f5-9b298366ce04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
