<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember me_okta-signin-submit</name>
   <tag></tag>
   <elementGuidId>38f17553-d5be-4f75-ae6d-5e5adff81453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='okta-signin-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#okta-signin-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58e884dc-8aec-43a6-a183-9f70c61a897a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-primary</value>
      <webElementGuid>345297bf-26f0-4193-9304-045e6a584d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>997a7604-c231-4d24-b3c0-2b0ddc72a52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>3ebc8f4e-5c6a-4694-9808-4e8c3c0c6ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>okta-signin-submit</value>
      <webElementGuid>d0ccf0b0-7486-4b90-be36-0c482a907924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>ce8f8e1a-215a-438c-817a-25b4702d0fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okta-signin-submit&quot;)</value>
      <webElementGuid>c27b2b7b-6109-499c-a52a-98962e69cf4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='okta-signin-submit']</value>
      <webElementGuid>fe4a9fd1-7d75-4fd5-8c19-37e24b703550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form19']/div[2]/input</value>
      <webElementGuid>a691c46a-0e6a-468e-93f7-2a4b5b1a92f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ef472407-cf4c-4753-917b-2f33c326287e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'okta-signin-submit']</value>
      <webElementGuid>3b3cc870-b64c-4c4d-b3ae-2a512a0b3db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
