<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UsernamePasswordRemember me</name>
   <tag></tag>
   <elementGuidId>00c2560a-a994-4142-809f-7494e3b4c477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-form-fieldset-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form19']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d1344f1-a25d-4336-bdea-6ff4fffe5416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-form-fieldset-container</value>
      <webElementGuid>1ff2a689-0cbd-49f9-8383-dfff832e7d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-se</name>
      <type>Main</type>
      <value>o-form-fieldset-container</value>
      <webElementGuid>b14360ce-a42d-457c-8f03-3f6c8da184ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username Password Remember me</value>
      <webElementGuid>d1d3c6e3-5816-4a96-91c2-4108b42100b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form19&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]</value>
      <webElementGuid>13fe3ceb-9a20-44be-a03b-4b52949161bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form19']/div/div[2]</value>
      <webElementGuid>adb2db64-e4a6-4878-b3f9-fce511ea2473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar Session 2'])[1]/following::div[2]</value>
      <webElementGuid>660bf8af-a901-4c6c-996d-86a1e1f3e71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>2dcd58c2-ceba-4970-a7e4-1222ac3ca86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Username Password Remember me' or . = 'Username Password Remember me')]</value>
      <webElementGuid>904646bd-8864-489f-b910-0c6188a4ab8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
